# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bbsdialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QRadioButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_BbsDialogClass(object):
    def setupUi(self, BbsDialogClass):
        if not BbsDialogClass.objectName():
            BbsDialogClass.setObjectName(u"BbsDialogClass")
        BbsDialogClass.resize(490, 430)
        self.tabWidget = QTabWidget(BbsDialogClass)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(5, 5, 480, 380))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 375, 330))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 100, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 100, 16))
        self.cBbsName = QComboBox(self.groupBox)
        self.cBbsName.setObjectName(u"cBbsName")
        self.cBbsName.setGeometry(QRect(110, 25, 141, 24))
        self.cConnectName = QLineEdit(self.groupBox)
        self.cConnectName.setObjectName(u"cConnectName")
        self.cConnectName.setGeometry(QRect(110, 65, 146, 22))
        self.cDescription = QPlainTextEdit(self.groupBox)
        self.cDescription.setObjectName(u"cDescription")
        self.cDescription.setGeometry(QRect(110, 105, 250, 64))
        self.label_20 = QLabel(self.groupBox)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 105, 100, 16))
        self.cNew = QPushButton(self.tab)
        self.cNew.setObjectName(u"cNew")
        self.cNew.setGeometry(QRect(395, 95, 75, 30))
        self.cCopy = QPushButton(self.tab)
        self.cCopy.setObjectName(u"cCopy")
        self.cCopy.setGeometry(QRect(395, 125, 75, 30))
        self.cDelete = QPushButton(self.tab)
        self.cDelete.setObjectName(u"cDelete")
        self.cDelete.setGeometry(QRect(395, 155, 75, 30))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 450, 330))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_3 = QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 450, 330))
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 100, 16))
        self.cCommandSend = QLineEdit(self.groupBox_3)
        self.cCommandSend.setObjectName(u"cCommandSend")
        self.cCommandSend.setGeometry(QRect(110, 25, 113, 22))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 55, 100, 16))
        self.cCommandSendBulletin = QLineEdit(self.groupBox_3)
        self.cCommandSendBulletin.setObjectName(u"cCommandSendBulletin")
        self.cCommandSendBulletin.setGeometry(QRect(110, 50, 113, 22))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 100, 16))
        self.cCommandSendNTS = QLineEdit(self.groupBox_3)
        self.cCommandSendNTS.setObjectName(u"cCommandSendNTS")
        self.cCommandSendNTS.setGeometry(QRect(110, 75, 113, 22))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 105, 100, 16))
        self.cCommandListMine = QLineEdit(self.groupBox_3)
        self.cCommandListMine.setObjectName(u"cCommandListMine")
        self.cCommandListMine.setGeometry(QRect(110, 100, 113, 22))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 130, 100, 16))
        self.cCommandListBulletin = QLineEdit(self.groupBox_3)
        self.cCommandListBulletin.setObjectName(u"cCommandListBulletin")
        self.cCommandListBulletin.setGeometry(QRect(110, 125, 113, 22))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 155, 100, 16))
        self.cCommandListNts = QLineEdit(self.groupBox_3)
        self.cCommandListNts.setObjectName(u"cCommandListNts")
        self.cCommandListNts.setGeometry(QRect(110, 150, 113, 22))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 180, 100, 16))
        self.cCommandListFiltered = QLineEdit(self.groupBox_3)
        self.cCommandListFiltered.setObjectName(u"cCommandListFiltered")
        self.cCommandListFiltered.setGeometry(QRect(110, 175, 113, 22))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 205, 100, 16))
        self.cCommandRead = QLineEdit(self.groupBox_3)
        self.cCommandRead.setObjectName(u"cCommandRead")
        self.cCommandRead.setGeometry(QRect(110, 200, 113, 22))
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 230, 100, 16))
        self.cCommandDelete = QLineEdit(self.groupBox_3)
        self.cCommandDelete.setObjectName(u"cCommandDelete")
        self.cCommandDelete.setGeometry(QRect(110, 225, 113, 22))
        self.cCommandBye = QLineEdit(self.groupBox_3)
        self.cCommandBye.setObjectName(u"cCommandBye")
        self.cCommandBye.setGeometry(QRect(110, 250, 113, 22))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 255, 100, 16))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_4 = QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 450, 330))
        self.cNeverSendInitCommands = QRadioButton(self.groupBox_4)
        self.cNeverSendInitCommands.setObjectName(u"cNeverSendInitCommands")
        self.cNeverSendInitCommands.setGeometry(QRect(10, 25, 425, 20))
        self.cAlwaysSendInitCommands = QRadioButton(self.groupBox_4)
        self.cAlwaysSendInitCommands.setObjectName(u"cAlwaysSendInitCommands")
        self.cAlwaysSendInitCommands.setGeometry(QRect(10, 50, 425, 40))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(15, 105, 175, 16))
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(230, 105, 175, 16))
        self.cCommandsBefore = QPlainTextEdit(self.groupBox_4)
        self.cCommandsBefore.setObjectName(u"cCommandsBefore")
        self.cCommandsBefore.setGeometry(QRect(20, 130, 150, 185))
        self.cCommandsAfter = QPlainTextEdit(self.groupBox_4)
        self.cCommandsAfter.setObjectName(u"cCommandsAfter")
        self.cCommandsAfter.setGeometry(QRect(235, 130, 150, 185))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_5 = QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 450, 330))
        self.cRetrievePrivateMessages = QCheckBox(self.groupBox_5)
        self.cRetrievePrivateMessages.setObjectName(u"cRetrievePrivateMessages")
        self.cRetrievePrivateMessages.setGeometry(QRect(15, 30, 210, 20))
        self.cRetrieveNtsMessages = QCheckBox(self.groupBox_5)
        self.cRetrieveNtsMessages.setObjectName(u"cRetrieveNtsMessages")
        self.cRetrieveNtsMessages.setGeometry(QRect(15, 60, 210, 20))
        self.cRetrieveBulletins = QCheckBox(self.groupBox_5)
        self.cRetrieveBulletins.setObjectName(u"cRetrieveBulletins")
        self.cRetrieveBulletins.setGeometry(QRect(15, 90, 210, 20))
        self.cSkipNtsMessagesThatISend = QCheckBox(self.groupBox_5)
        self.cSkipNtsMessagesThatISend.setObjectName(u"cSkipNtsMessagesThatISend")
        self.cSkipNtsMessagesThatISend.setGeometry(QRect(225, 30, 220, 20))
        self.cSkipBulletinsThatISend = QCheckBox(self.groupBox_5)
        self.cSkipBulletinsThatISend.setObjectName(u"cSkipBulletinsThatISend")
        self.cSkipBulletinsThatISend.setGeometry(QRect(225, 60, 210, 20))
        self.cKeepMessagesOnBBS = QCheckBox(self.groupBox_5)
        self.cKeepMessagesOnBBS.setObjectName(u"cKeepMessagesOnBBS")
        self.cKeepMessagesOnBBS.setGeometry(QRect(225, 90, 210, 20))
        self.cAllNewBulletins = QRadioButton(self.groupBox_5)
        self.cAllNewBulletins.setObjectName(u"cAllNewBulletins")
        self.cAllNewBulletins.setGeometry(QRect(35, 115, 140, 20))
        self.cSelectedBulletins = QRadioButton(self.groupBox_5)
        self.cSelectedBulletins.setObjectName(u"cSelectedBulletins")
        self.cSelectedBulletins.setGeometry(QRect(35, 145, 140, 20))
        self.cCustomRetrieval = QRadioButton(self.groupBox_5)
        self.cCustomRetrieval.setObjectName(u"cCustomRetrieval")
        self.cCustomRetrieval.setGeometry(QRect(35, 210, 140, 20))
        self.plainTextEdit = QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(195, 140, 180, 64))
        self.plainTextEdit_2 = QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(195, 205, 180, 95))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.groupBox_6 = QGroupBox(self.tab_6)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 450, 330))
        self.tabWidget.addTab(self.tab_6, "")
        self.cOK = QPushButton(BbsDialogClass)
        self.cOK.setObjectName(u"cOK")
        self.cOK.setGeometry(QRect(335, 395, 75, 30))
        self.cCancel = QPushButton(BbsDialogClass)
        self.cCancel.setObjectName(u"cCancel")
        self.cCancel.setGeometry(QRect(410, 395, 75, 30))

        self.retranslateUi(BbsDialogClass)
        self.cOK.clicked.connect(BbsDialogClass.accept)
        self.cCancel.clicked.connect(BbsDialogClass.reject)

        self.tabWidget.setCurrentIndex(0)

    # setupUi

    def retranslateUi(self, BbsDialogClass):
        BbsDialogClass.setWindowTitle(QCoreApplication.translate("BbsDialogClass", u"BbsDialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("BbsDialogClass", u"BBS Name", None))
        self.label.setText(QCoreApplication.translate("BbsDialogClass", u"BBS name", None))
        self.label_2.setText(QCoreApplication.translate("BbsDialogClass", u"Connect name", None))
        self.label_20.setText(QCoreApplication.translate("BbsDialogClass", u"Description", None))
        self.cNew.setText(QCoreApplication.translate("BbsDialogClass", u"New", None))
        self.cCopy.setText(QCoreApplication.translate("BbsDialogClass", u"Copy", None))
        self.cDelete.setText(QCoreApplication.translate("BbsDialogClass", u"Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("BbsDialogClass", u"Name", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("BbsDialogClass", u"GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("BbsDialogClass", u"Prompts", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("BbsDialogClass", u"Commands", None))
        self.label_4.setText(QCoreApplication.translate("BbsDialogClass", u"Send", None))
        self.label_5.setText(QCoreApplication.translate("BbsDialogClass", u"Send bulletin", None))
        self.label_6.setText(QCoreApplication.translate("BbsDialogClass", u"Send NTS", None))
        self.label_7.setText(QCoreApplication.translate("BbsDialogClass", u"List mine", None))
        self.label_8.setText(QCoreApplication.translate("BbsDialogClass", u"List bulletin", None))
        self.label_9.setText(QCoreApplication.translate("BbsDialogClass", u"List NTS", None))
        self.label_10.setText(QCoreApplication.translate("BbsDialogClass", u"List filtered", None))
        self.label_11.setText(QCoreApplication.translate("BbsDialogClass", u"Read", None))
        self.label_12.setText(QCoreApplication.translate("BbsDialogClass", u"Delete", None))
        self.label_13.setText(QCoreApplication.translate("BbsDialogClass", u"Bye / log off", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("BbsDialogClass", u"Commands", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("BbsDialogClass", u"Initialization Commands", None))
        self.cNeverSendInitCommands.setText(QCoreApplication.translate("BbsDialogClass", u"Never send BBS initalization commands", None))
        self.cAlwaysSendInitCommands.setText(QCoreApplication.translate("BbsDialogClass", u"Send BBS initialization commands for every \n"
"Send/Recevive (S/R) session", None))
        self.label_18.setText(QCoreApplication.translate("BbsDialogClass", u"Cmds to send before S/R", None))
        self.label_19.setText(QCoreApplication.translate("BbsDialogClass", u"Cmds to send after S/R", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("BbsDialogClass", u"Init Commands", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("BbsDialogClass", u"Retrieve These Messages", None))
        self.cRetrievePrivateMessages.setText(QCoreApplication.translate("BbsDialogClass", u"Retrieve private messages", None))
        self.cRetrieveNtsMessages.setText(QCoreApplication.translate("BbsDialogClass", u"Retrieve NTS messages", None))
        self.cRetrieveBulletins.setText(QCoreApplication.translate("BbsDialogClass", u"Retrieve bulletins", None))
        self.cSkipNtsMessagesThatISend.setText(QCoreApplication.translate("BbsDialogClass", u"Skip NTS messages that I send", None))
        self.cSkipBulletinsThatISend.setText(QCoreApplication.translate("BbsDialogClass", u"Skip bulletins that I send", None))
        self.cKeepMessagesOnBBS.setText(QCoreApplication.translate("BbsDialogClass", u"Keep messages on BBS", None))
        self.cAllNewBulletins.setText(QCoreApplication.translate("BbsDialogClass", u"All new bulletins", None))
        self.cSelectedBulletins.setText(QCoreApplication.translate("BbsDialogClass", u"Selected bulletins", None))
        self.cCustomRetrieval.setText(QCoreApplication.translate("BbsDialogClass", u"Custom retrieval", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("BbsDialogClass", u"Retrieving", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("BbsDialogClass", u"GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("BbsDialogClass", u"Path", None))
        self.cOK.setText(QCoreApplication.translate("BbsDialogClass", u"OK", None))
        self.cCancel.setText(QCoreApplication.translate("BbsDialogClass", u"Cancel", None))
    # retranslateUi

