# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ics309builder.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDateTimeEdit, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_Ics309Builder(object):
    def setupUi(self, Ics309Builder):
        if not Ics309Builder.objectName():
            Ics309Builder.setObjectName(u"Ics309Builder")
        Ics309Builder.resize(612, 600)
        self.actionSave_As_txt = QAction(Ics309Builder)
        self.actionSave_As_txt.setObjectName(u"actionSave_As_txt")
        self.actionSave_As_csv = QAction(Ics309Builder)
        self.actionSave_As_csv.setObjectName(u"actionSave_As_csv")
        self.actionReload = QAction(Ics309Builder)
        self.actionReload.setObjectName(u"actionReload")
        self.actionPrint = QAction(Ics309Builder)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionPrint_Setup = QAction(Ics309Builder)
        self.actionPrint_Setup.setObjectName(u"actionPrint_Setup")
        self.actionExit = QAction(Ics309Builder)
        self.actionExit.setObjectName(u"actionExit")
        self.actionCut = QAction(Ics309Builder)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(Ics309Builder)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionast = QAction(Ics309Builder)
        self.actionast.setObjectName(u"actionast")
        self.actionSelect_All = QAction(Ics309Builder)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionAbout = QAction(Ics309Builder)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(Ics309Builder)
        self.centralwidget.setObjectName(u"centralwidget")
        self.c_build_data_set = QPushButton(self.centralwidget)
        self.c_build_data_set.setObjectName(u"c_build_data_set")
        self.c_build_data_set.setGeometry(QRect(5, 10, 120, 30))
        self.c_print = QPushButton(self.centralwidget)
        self.c_print.setObjectName(u"c_print")
        self.c_print.setGeometry(QRect(130, 10, 75, 30))
        self.c_exit = QPushButton(self.centralwidget)
        self.c_exit.setObjectName(u"c_exit")
        self.c_exit.setGeometry(QRect(210, 10, 75, 30))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(300, 55, 150, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 150, 295, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 100, 280, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 55, 280, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 150, 265, 16))
        self.c_tactical_info = QLineEdit(self.centralwidget)
        self.c_tactical_info.setObjectName(u"c_tactical_info")
        self.c_tactical_info.setGeometry(QRect(10, 170, 280, 22))
        self.c_activation_number = QLineEdit(self.centralwidget)
        self.c_activation_number.setObjectName(u"c_activation_number")
        self.c_activation_number.setGeometry(QRect(10, 120, 280, 22))
        self.c_incident_name = QLineEdit(self.centralwidget)
        self.c_incident_name.setObjectName(u"c_incident_name")
        self.c_incident_name.setGeometry(QRect(10, 75, 280, 22))
        self.c_user_info = QLineEdit(self.centralwidget)
        self.c_user_info.setObjectName(u"c_user_info")
        self.c_user_info.setGeometry(QRect(300, 170, 265, 22))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 205, 555, 261))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.c_page1_today = QRadioButton(self.tab_6)
        self.c_page1_today.setObjectName(u"c_page1_today")
        self.c_page1_today.setGeometry(QRect(15, 20, 170, 20))
        self.c_page1_since_last = QRadioButton(self.tab_6)
        self.c_page1_since_last.setObjectName(u"c_page1_since_last")
        self.c_page1_since_last.setGeometry(QRect(15, 45, 170, 20))
        self.c_page1_all = QRadioButton(self.tab_6)
        self.c_page1_all.setObjectName(u"c_page1_all")
        self.c_page1_all.setGeometry(QRect(15, 70, 170, 20))
        self.c_page1_custom_range = QRadioButton(self.tab_6)
        self.c_page1_custom_range.setObjectName(u"c_page1_custom_range")
        self.c_page1_custom_range.setGeometry(QRect(15, 95, 170, 20))
        self.label_12 = QLabel(self.tab_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 145, 49, 16))
        self.label_7 = QLabel(self.tab_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 120, 49, 16))
        self.c_page1_custom_range_to = QDateTimeEdit(self.tab_6)
        self.c_page1_custom_range_to.setObjectName(u"c_page1_custom_range_to")
        self.c_page1_custom_range_to.setGeometry(QRect(85, 140, 160, 24))
        self.c_page1_custom_range_to.setDateTime(QDateTime(QDate(2026, 4, 24), QTime(0, 0, 0)))
        self.c_page1_custom_range_to.setDate(QDate(2026, 4, 24))
        self.c_page1_custom_range_to.setMinimumDateTime(QDateTime(QDate(2020, 1, 1), QTime(0, 0, 0)))
        self.c_page1_custom_range_to.setCalendarPopup(True)
        self.c_page1_custom_range_from = QDateTimeEdit(self.tab_6)
        self.c_page1_custom_range_from.setObjectName(u"c_page1_custom_range_from")
        self.c_page1_custom_range_from.setGeometry(QRect(85, 115, 160, 24))
        self.c_page1_custom_range_from.setDateTime(QDateTime(QDate(2026, 4, 24), QTime(0, 0, 0)))
        self.c_page1_custom_range_from.setDate(QDate(2026, 4, 24))
        self.c_page1_custom_range_from.setMinimumDateTime(QDateTime(QDate(2020, 1, 1), QTime(0, 0, 0)))
        self.c_page1_custom_range_from.setCalendarPopup(True)
        self.tabWidget.addTab(self.tab_6, "")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(330, 80, 49, 16))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(330, 105, 49, 16))
        self.c_operational_period_from = QDateTimeEdit(self.centralwidget)
        self.c_operational_period_from.setObjectName(u"c_operational_period_from")
        self.c_operational_period_from.setGeometry(QRect(375, 75, 160, 24))
        self.c_operational_period_from.setDateTime(QDateTime(QDate(2026, 4, 24), QTime(0, 0, 0)))
        self.c_operational_period_from.setDate(QDate(2026, 4, 24))
        self.c_operational_period_from.setMinimumDateTime(QDateTime(QDate(2020, 1, 1), QTime(0, 0, 0)))
        self.c_operational_period_from.setCalendarPopup(True)
        self.c_operational_period_to = QDateTimeEdit(self.centralwidget)
        self.c_operational_period_to.setObjectName(u"c_operational_period_to")
        self.c_operational_period_to.setGeometry(QRect(375, 100, 160, 24))
        self.c_operational_period_to.setDateTime(QDateTime(QDate(2026, 4, 24), QTime(0, 0, 0)))
        self.c_operational_period_to.setDate(QDate(2026, 4, 24))
        self.c_operational_period_to.setMinimumDateTime(QDateTime(QDate(2020, 1, 1), QTime(0, 0, 0)))
        self.c_operational_period_to.setCalendarPopup(True)
        Ics309Builder.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Ics309Builder)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 612, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        Ics309Builder.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Ics309Builder)
        self.statusbar.setObjectName(u"statusbar")
        Ics309Builder.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.c_build_data_set, self.c_print)
        QWidget.setTabOrder(self.c_print, self.c_exit)
        QWidget.setTabOrder(self.c_exit, self.c_incident_name)
        QWidget.setTabOrder(self.c_incident_name, self.c_activation_number)
        QWidget.setTabOrder(self.c_activation_number, self.c_operational_period_from)
        QWidget.setTabOrder(self.c_operational_period_from, self.c_operational_period_to)
        QWidget.setTabOrder(self.c_operational_period_to, self.c_tactical_info)
        QWidget.setTabOrder(self.c_tactical_info, self.c_user_info)
        QWidget.setTabOrder(self.c_user_info, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.c_page1_today)
        QWidget.setTabOrder(self.c_page1_today, self.c_page1_since_last)
        QWidget.setTabOrder(self.c_page1_since_last, self.c_page1_all)
        QWidget.setTabOrder(self.c_page1_all, self.c_page1_custom_range)
        QWidget.setTabOrder(self.c_page1_custom_range, self.c_page1_custom_range_from)
        QWidget.setTabOrder(self.c_page1_custom_range_from, self.c_page1_custom_range_to)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSave_As_txt)
        self.menuFile.addAction(self.actionSave_As_csv)
        self.menuFile.addAction(self.actionReload)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Setup)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionast)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(Ics309Builder)

        self.tabWidget.setCurrentIndex(5)

    # setupUi

    def retranslateUi(self, Ics309Builder):
        Ics309Builder.setWindowTitle(QCoreApplication.translate("Ics309Builder", u"MainWindow", None))
        self.actionSave_As_txt.setText(QCoreApplication.translate("Ics309Builder", u"Save As .txt...", None))
        self.actionSave_As_csv.setText(QCoreApplication.translate("Ics309Builder", u"Save As .csv", None))
        self.actionReload.setText(QCoreApplication.translate("Ics309Builder", u"Reload", None))
        self.actionPrint.setText(QCoreApplication.translate("Ics309Builder", u"Print...", None))
        self.actionPrint_Setup.setText(QCoreApplication.translate("Ics309Builder", u"Print Setup...", None))
        self.actionExit.setText(QCoreApplication.translate("Ics309Builder", u"Exit", None))
        self.actionCut.setText(QCoreApplication.translate("Ics309Builder", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("Ics309Builder", u"Copy", None))
        self.actionast.setText(QCoreApplication.translate("Ics309Builder", u"Paste", None))
        self.actionSelect_All.setText(QCoreApplication.translate("Ics309Builder", u"Select All", None))
        self.actionAbout.setText(QCoreApplication.translate("Ics309Builder", u"About", None))
        self.c_build_data_set.setText(QCoreApplication.translate("Ics309Builder", u"Build Data Set", None))
        self.c_print.setText(QCoreApplication.translate("Ics309Builder", u"Print", None))
        self.c_exit.setText(QCoreApplication.translate("Ics309Builder", u"Exit", None))
        self.label.setText(QCoreApplication.translate("Ics309Builder", u"Operational Period", None))
        self.label_2.setText(QCoreApplication.translate("Ics309Builder", u"Radio Net Name or Position / Tac Call", None))
        self.label_3.setText(QCoreApplication.translate("Ics309Builder", u"Activation Number", None))
        self.label_5.setText(QCoreApplication.translate("Ics309Builder", u"Incident Name", None))
        self.label_6.setText(QCoreApplication.translate("Ics309Builder", u"Radio Operator Name / Call", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Ics309Builder", u"Period", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Ics309Builder", u"Content", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Ics309Builder", u"Sort", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Ics309Builder", u"Layout", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Ics309Builder", u"Output", None))
        self.c_page1_today.setText(QCoreApplication.translate("Ics309Builder", u"Today", None))
        self.c_page1_since_last.setText(QCoreApplication.translate("Ics309Builder", u"Since last report run", None))
        self.c_page1_all.setText(QCoreApplication.translate("Ics309Builder", u"All ", None))
        self.c_page1_custom_range.setText(QCoreApplication.translate("Ics309Builder", u"Custom range", None))
        self.label_12.setText(QCoreApplication.translate("Ics309Builder", u"To", None))
        self.label_7.setText(QCoreApplication.translate("Ics309Builder", u"From", None))
        self.c_page1_custom_range_to.setDisplayFormat(QCoreApplication.translate("Ics309Builder", u"MM-dd-yyyy HH:mm", None))
        self.c_page1_custom_range_from.setDisplayFormat(QCoreApplication.translate("Ics309Builder", u"MM-dd-yyyy HH:mm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Ics309Builder", u"e-Signature", None))
        self.label_4.setText(QCoreApplication.translate("Ics309Builder", u"From", None))
        self.label_11.setText(QCoreApplication.translate("Ics309Builder", u"To", None))
        self.c_operational_period_from.setDisplayFormat(QCoreApplication.translate("Ics309Builder", u"MM-dd-yyyy HH:mm", None))
        self.c_operational_period_to.setDisplayFormat(QCoreApplication.translate("Ics309Builder", u"MM-dd-yyyy HH:mm", None))
        self.menuFile.setTitle(QCoreApplication.translate("Ics309Builder", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("Ics309Builder", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("Ics309Builder", u"Help", None))
    # retranslateUi

