# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfacedialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QRadioButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_InterfaceDialogClass(object):
    def setupUi(self, InterfaceDialogClass):
        if not InterfaceDialogClass.objectName():
            InterfaceDialogClass.setObjectName(u"InterfaceDialogClass")
        InterfaceDialogClass.resize(491, 430)
        self.tabWidget = QTabWidget(InterfaceDialogClass)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(5, 5, 480, 380))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 375, 270))
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 30, 100, 16))
        self.cInterfaceName = QComboBox(self.groupBox)
        self.cInterfaceName.setObjectName(u"cInterfaceName")
        self.cInterfaceName.setGeometry(QRect(110, 25, 250, 24))
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 60, 100, 16))
        self.cDescription = QPlainTextEdit(self.groupBox)
        self.cDescription.setObjectName(u"cDescription")
        self.cDescription.setGeometry(QRect(110, 60, 250, 64))
        self.cDelete = QPushButton(self.tab)
        self.cDelete.setObjectName(u"cDelete")
        self.cDelete.setGeometry(QRect(395, 155, 75, 30))
        self.cCopy = QPushButton(self.tab)
        self.cCopy.setObjectName(u"cCopy")
        self.cCopy.setGeometry(QRect(395, 125, 75, 30))
        self.cNew = QPushButton(self.tab)
        self.cNew.setObjectName(u"cNew")
        self.cNew.setGeometry(QRect(395, 95, 75, 30))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 450, 136))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 100, 16))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 55, 100, 16))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 100, 16))
        self.cPromptCommand = QLineEdit(self.groupBox_2)
        self.cPromptCommand.setObjectName(u"cPromptCommand")
        self.cPromptCommand.setGeometry(QRect(110, 25, 150, 22))
        self.cPromptTimeout = QLineEdit(self.groupBox_2)
        self.cPromptTimeout.setObjectName(u"cPromptTimeout")
        self.cPromptTimeout.setGeometry(QRect(110, 50, 150, 22))
        self.cPromptConnected = QLineEdit(self.groupBox_2)
        self.cPromptConnected.setObjectName(u"cPromptConnected")
        self.cPromptConnected.setGeometry(QRect(110, 75, 150, 22))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 105, 100, 16))
        self.cPromptDisconnected = QLineEdit(self.groupBox_2)
        self.cPromptDisconnected.setObjectName(u"cPromptDisconnected")
        self.cPromptDisconnected.setGeometry(QRect(110, 100, 150, 22))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_3 = QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 450, 171))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 25, 90, 22))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 90, 22))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 75, 90, 22))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 100, 90, 22))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 125, 90, 22))
        self.cCommandMyCall = QLineEdit(self.groupBox_3)
        self.cCommandMyCall.setObjectName(u"cCommandMyCall")
        self.cCommandMyCall.setGeometry(QRect(100, 25, 113, 22))
        self.cCommandConnect = QLineEdit(self.groupBox_3)
        self.cCommandConnect.setObjectName(u"cCommandConnect")
        self.cCommandConnect.setGeometry(QRect(100, 50, 113, 22))
        self.cCommandRetry = QLineEdit(self.groupBox_3)
        self.cCommandRetry.setObjectName(u"cCommandRetry")
        self.cCommandRetry.setGeometry(QRect(100, 75, 113, 22))
        self.cCommandConvers = QLineEdit(self.groupBox_3)
        self.cCommandConvers.setObjectName(u"cCommandConvers")
        self.cCommandConvers.setGeometry(QRect(100, 100, 113, 22))
        self.cCommandDayTime = QLineEdit(self.groupBox_3)
        self.cCommandDayTime.setObjectName(u"cCommandDayTime")
        self.cCommandDayTime.setGeometry(QRect(100, 125, 113, 22))
        self.groupBox_7 = QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 180, 450, 81))
        self.cIncludeCommandPrefix = QCheckBox(self.groupBox_7)
        self.cIncludeCommandPrefix.setObjectName(u"cIncludeCommandPrefix")
        self.cIncludeCommandPrefix.setGeometry(QRect(10, 30, 230, 22))
        self.cCommandPrefix = QLineEdit(self.groupBox_7)
        self.cCommandPrefix.setObjectName(u"cCommandPrefix")
        self.cCommandPrefix.setGeometry(QRect(240, 30, 35, 22))
        self.label_20 = QLabel(self.groupBox_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(285, 30, 145, 22))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_4 = QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 450, 330))
        self.cNeverSendInitCommands = QRadioButton(self.groupBox_4)
        self.cNeverSendInitCommands.setObjectName(u"cNeverSendInitCommands")
        self.cNeverSendInitCommands.setGeometry(QRect(10, 25, 425, 20))
        self.cAlwaysSendInitCommands = QRadioButton(self.groupBox_4)
        self.cAlwaysSendInitCommands.setObjectName(u"cAlwaysSendInitCommands")
        self.cAlwaysSendInitCommands.setGeometry(QRect(10, 50, 425, 40))
        self.label = QLabel(self.groupBox_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 105, 175, 16))
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(230, 105, 175, 16))
        self.cCommandsBefore = QPlainTextEdit(self.groupBox_4)
        self.cCommandsBefore.setObjectName(u"cCommandsBefore")
        self.cCommandsBefore.setGeometry(QRect(20, 130, 150, 185))
        self.cCommandsAfter = QPlainTextEdit(self.groupBox_4)
        self.cCommandsAfter.setObjectName(u"cCommandsAfter")
        self.cCommandsAfter.setGeometry(QRect(235, 130, 150, 185))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_5 = QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 450, 196))
        self.cStopBits = QComboBox(self.groupBox_5)
        self.cStopBits.addItem("")
        self.cStopBits.addItem("")
        self.cStopBits.addItem("")
        self.cStopBits.setObjectName(u"cStopBits")
        self.cStopBits.setGeometry(QRect(110, 125, 90, 24))
        self.cComPort = QComboBox(self.groupBox_5)
        self.cComPort.setObjectName(u"cComPort")
        self.cComPort.setGeometry(QRect(110, 25, 325, 24))
        self.label_15 = QLabel(self.groupBox_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(15, 80, 90, 16))
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(15, 30, 90, 16))
        self.cBaud = QComboBox(self.groupBox_5)
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.addItem("")
        self.cBaud.setObjectName(u"cBaud")
        self.cBaud.setGeometry(QRect(110, 50, 90, 24))
        self.cDataBits = QComboBox(self.groupBox_5)
        self.cDataBits.addItem("")
        self.cDataBits.addItem("")
        self.cDataBits.addItem("")
        self.cDataBits.addItem("")
        self.cDataBits.setObjectName(u"cDataBits")
        self.cDataBits.setGeometry(QRect(110, 100, 90, 24))
        self.cParity = QComboBox(self.groupBox_5)
        self.cParity.addItem("")
        self.cParity.addItem("")
        self.cParity.addItem("")
        self.cParity.addItem("")
        self.cParity.addItem("")
        self.cParity.setObjectName(u"cParity")
        self.cParity.setGeometry(QRect(110, 75, 90, 24))
        self.label_16 = QLabel(self.groupBox_5)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(15, 130, 90, 16))
        self.label_13 = QLabel(self.groupBox_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(15, 55, 90, 16))
        self.label_14 = QLabel(self.groupBox_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(15, 105, 90, 16))
        self.cFlowControl = QComboBox(self.groupBox_5)
        self.cFlowControl.addItem("")
        self.cFlowControl.addItem("")
        self.cFlowControl.setObjectName(u"cFlowControl")
        self.cFlowControl.setGeometry(QRect(110, 150, 90, 24))
        self.label_17 = QLabel(self.groupBox_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(15, 155, 90, 16))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.groupBox_6 = QGroupBox(self.tab_6)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 450, 310))
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.groupBox_8 = QGroupBox(self.tab_7)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 10, 450, 310))
        self.tabWidget.addTab(self.tab_7, "")
        self.cOK = QPushButton(InterfaceDialogClass)
        self.cOK.setObjectName(u"cOK")
        self.cOK.setGeometry(QRect(335, 395, 75, 30))
        self.cCancel = QPushButton(InterfaceDialogClass)
        self.cCancel.setObjectName(u"cCancel")
        self.cCancel.setGeometry(QRect(410, 395, 75, 30))
        QWidget.setTabOrder(self.tabWidget, self.cFlowControl)
        QWidget.setTabOrder(self.cFlowControl, self.cPromptCommand)
        QWidget.setTabOrder(self.cPromptCommand, self.cPromptTimeout)
        QWidget.setTabOrder(self.cPromptTimeout, self.cPromptConnected)
        QWidget.setTabOrder(self.cPromptConnected, self.cPromptDisconnected)
        QWidget.setTabOrder(self.cPromptDisconnected, self.cCommandMyCall)
        QWidget.setTabOrder(self.cCommandMyCall, self.cCommandConnect)
        QWidget.setTabOrder(self.cCommandConnect, self.cCommandRetry)
        QWidget.setTabOrder(self.cCommandRetry, self.cCommandConvers)
        QWidget.setTabOrder(self.cCommandConvers, self.cCommandDayTime)
        QWidget.setTabOrder(self.cCommandDayTime, self.cNeverSendInitCommands)
        QWidget.setTabOrder(self.cNeverSendInitCommands, self.cAlwaysSendInitCommands)
        QWidget.setTabOrder(self.cAlwaysSendInitCommands, self.cComPort)
        QWidget.setTabOrder(self.cComPort, self.cBaud)
        QWidget.setTabOrder(self.cBaud, self.cParity)
        QWidget.setTabOrder(self.cParity, self.cDataBits)
        QWidget.setTabOrder(self.cDataBits, self.cStopBits)

        self.retranslateUi(InterfaceDialogClass)
        self.cOK.clicked.connect(InterfaceDialogClass.accept)
        self.cCancel.clicked.connect(InterfaceDialogClass.reject)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(InterfaceDialogClass)
    # setupUi

    def retranslateUi(self, InterfaceDialogClass):
        InterfaceDialogClass.setWindowTitle(QCoreApplication.translate("InterfaceDialogClass", u"InterfaceDialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"Choose a Name", None))
        self.label_18.setText(QCoreApplication.translate("InterfaceDialogClass", u"IF name", None))
        self.label_19.setText(QCoreApplication.translate("InterfaceDialogClass", u"Description", None))
        self.cDelete.setText(QCoreApplication.translate("InterfaceDialogClass", u"Delete", None))
        self.cCopy.setText(QCoreApplication.translate("InterfaceDialogClass", u"Copy", None))
        self.cNew.setText(QCoreApplication.translate("InterfaceDialogClass", u"New", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("InterfaceDialogClass", u"Type", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"Prompts", None))
        self.label_3.setText(QCoreApplication.translate("InterfaceDialogClass", u"Command", None))
        self.label_4.setText(QCoreApplication.translate("InterfaceDialogClass", u"Timeout", None))
        self.label_5.setText(QCoreApplication.translate("InterfaceDialogClass", u"Connected", None))
        self.label_6.setText(QCoreApplication.translate("InterfaceDialogClass", u"Disconnected", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("InterfaceDialogClass", u"Prompts", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"Commands", None))
        self.label_7.setText(QCoreApplication.translate("InterfaceDialogClass", u"Mycall", None))
        self.label_8.setText(QCoreApplication.translate("InterfaceDialogClass", u"Connect", None))
        self.label_9.setText(QCoreApplication.translate("InterfaceDialogClass", u"Retry", None))
        self.label_10.setText(QCoreApplication.translate("InterfaceDialogClass", u"Convers", None))
        self.label_11.setText(QCoreApplication.translate("InterfaceDialogClass", u"DayTime", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"TNC Command Prefix", None))
        self.cIncludeCommandPrefix.setText(QCoreApplication.translate("InterfaceDialogClass", u"Include TNC command prefix", None))
        self.label_20.setText(QCoreApplication.translate("InterfaceDialogClass", u"(single number only)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("InterfaceDialogClass", u"TNC Cmds", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"Initialization Commands", None))
        self.cNeverSendInitCommands.setText(QCoreApplication.translate("InterfaceDialogClass", u"Never send TNC initalization commands", None))
        self.cAlwaysSendInitCommands.setText(QCoreApplication.translate("InterfaceDialogClass", u"Send TNC initialization commands for every\n"
"Send/Recevive (S/R) session", None))
        self.label.setText(QCoreApplication.translate("InterfaceDialogClass", u"Cmds to send before S/R", None))
        self.label_2.setText(QCoreApplication.translate("InterfaceDialogClass", u"Cmds to send after S/R", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("InterfaceDialogClass", u"Init Cmds", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"Comm Port Settings", None))
        self.cStopBits.setItemText(0, QCoreApplication.translate("InterfaceDialogClass", u"1", None))
        self.cStopBits.setItemText(1, QCoreApplication.translate("InterfaceDialogClass", u"1.5", None))
        self.cStopBits.setItemText(2, QCoreApplication.translate("InterfaceDialogClass", u"2", None))

        self.label_15.setText(QCoreApplication.translate("InterfaceDialogClass", u"Parity", None))
        self.label_12.setText(QCoreApplication.translate("InterfaceDialogClass", u"Com port", None))
        self.cBaud.setItemText(0, QCoreApplication.translate("InterfaceDialogClass", u"110", None))
        self.cBaud.setItemText(1, QCoreApplication.translate("InterfaceDialogClass", u"300", None))
        self.cBaud.setItemText(2, QCoreApplication.translate("InterfaceDialogClass", u"600", None))
        self.cBaud.setItemText(3, QCoreApplication.translate("InterfaceDialogClass", u"1200", None))
        self.cBaud.setItemText(4, QCoreApplication.translate("InterfaceDialogClass", u"2400", None))
        self.cBaud.setItemText(5, QCoreApplication.translate("InterfaceDialogClass", u"4800", None))
        self.cBaud.setItemText(6, QCoreApplication.translate("InterfaceDialogClass", u"9600", None))
        self.cBaud.setItemText(7, QCoreApplication.translate("InterfaceDialogClass", u"14400", None))
        self.cBaud.setItemText(8, QCoreApplication.translate("InterfaceDialogClass", u"19200", None))
        self.cBaud.setItemText(9, QCoreApplication.translate("InterfaceDialogClass", u"38400", None))
        self.cBaud.setItemText(10, QCoreApplication.translate("InterfaceDialogClass", u"57600", None))
        self.cBaud.setItemText(11, QCoreApplication.translate("InterfaceDialogClass", u"115200", None))
        self.cBaud.setItemText(12, QCoreApplication.translate("InterfaceDialogClass", u"128000", None))
        self.cBaud.setItemText(13, QCoreApplication.translate("InterfaceDialogClass", u"256000", None))

        self.cDataBits.setItemText(0, QCoreApplication.translate("InterfaceDialogClass", u"5", None))
        self.cDataBits.setItemText(1, QCoreApplication.translate("InterfaceDialogClass", u"6", None))
        self.cDataBits.setItemText(2, QCoreApplication.translate("InterfaceDialogClass", u"7", None))
        self.cDataBits.setItemText(3, QCoreApplication.translate("InterfaceDialogClass", u"8", None))

        self.cParity.setItemText(0, QCoreApplication.translate("InterfaceDialogClass", u"Even", None))
        self.cParity.setItemText(1, QCoreApplication.translate("InterfaceDialogClass", u"Odd", None))
        self.cParity.setItemText(2, QCoreApplication.translate("InterfaceDialogClass", u"None", None))
        self.cParity.setItemText(3, QCoreApplication.translate("InterfaceDialogClass", u"Mark", None))
        self.cParity.setItemText(4, QCoreApplication.translate("InterfaceDialogClass", u"Space", None))

        self.label_16.setText(QCoreApplication.translate("InterfaceDialogClass", u"Stop bits", None))
        self.label_13.setText(QCoreApplication.translate("InterfaceDialogClass", u"Baud", None))
        self.label_14.setText(QCoreApplication.translate("InterfaceDialogClass", u"Data bits", None))
        self.cFlowControl.setItemText(0, QCoreApplication.translate("InterfaceDialogClass", u"None", None))
        self.cFlowControl.setItemText(1, QCoreApplication.translate("InterfaceDialogClass", u"RTS/CTS", None))

        self.label_17.setText(QCoreApplication.translate("InterfaceDialogClass", u"Flow control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("InterfaceDialogClass", u"Com Port", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("InterfaceDialogClass", u"AGWPE", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("InterfaceDialogClass", u"GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("InterfaceDialogClass", u"Telnet", None))
        self.cOK.setText(QCoreApplication.translate("InterfaceDialogClass", u"OK", None))
        self.cCancel.setText(QCoreApplication.translate("InterfaceDialogClass", u"Cancel", None))
    # retranslateUi

