# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QGroupBox,
    QHeaderView, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindowClass(object):
    def setupUi(self, MainWindowClass):
        if not MainWindowClass.objectName():
            MainWindowClass.setObjectName(u"MainWindowClass")
        MainWindowClass.resize(1276, 649)
        self.actionBBS = QAction(MainWindowClass)
        self.actionBBS.setObjectName(u"actionBBS")
        self.actionInterface = QAction(MainWindowClass)
        self.actionInterface.setObjectName(u"actionInterface")
        self.actionStation_ID = QAction(MainWindowClass)
        self.actionStation_ID.setObjectName(u"actionStation_ID")
        self.mSetupAddress_Book = QAction(MainWindowClass)
        self.mSetupAddress_Book.setObjectName(u"mSetupAddress_Book")
        self.actionComputer_Time_Check = QAction(MainWindowClass)
        self.actionComputer_Time_Check.setObjectName(u"actionComputer_Time_Check")
        self.actionNewProfile = QAction(MainWindowClass)
        self.actionNewProfile.setObjectName(u"actionNewProfile")
        self.actionSaveProfile = QAction(MainWindowClass)
        self.actionSaveProfile.setObjectName(u"actionSaveProfile")
        self.actionDeleteProfile = QAction(MainWindowClass)
        self.actionDeleteProfile.setObjectName(u"actionDeleteProfile")
        self.actionNew_Message = QAction(MainWindowClass)
        self.actionNew_Message.setObjectName(u"actionNew_Message")
        self.actionSave_As = QAction(MainWindowClass)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As_No_Headers = QAction(MainWindowClass)
        self.actionSave_As_No_Headers.setObjectName(u"actionSave_As_No_Headers")
        self.actionSave_All = QAction(MainWindowClass)
        self.actionSave_All.setObjectName(u"actionSave_All")
        self.actionExport = QAction(MainWindowClass)
        self.actionExport.setObjectName(u"actionExport")
        self.actionImport = QAction(MainWindowClass)
        self.actionImport.setObjectName(u"actionImport")
        self.actionDelete_All_Messages = QAction(MainWindowClass)
        self.actionDelete_All_Messages.setObjectName(u"actionDelete_All_Messages")
        self.actionPrint = QAction(MainWindowClass)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionPrint_No_Headers = QAction(MainWindowClass)
        self.actionPrint_No_Headers.setObjectName(u"actionPrint_No_Headers")
        self.actionPrint_Setup = QAction(MainWindowClass)
        self.actionPrint_Setup.setObjectName(u"actionPrint_Setup")
        self.actionExit = QAction(MainWindowClass)
        self.actionExit.setObjectName(u"actionExit")
        self.actionCopy = QAction(MainWindowClass)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionCut = QAction(MainWindowClass)
        self.actionCut.setObjectName(u"actionCut")
        self.actionPaste = QAction(MainWindowClass)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionSelectAll = QAction(MainWindowClass)
        self.actionSelectAll.setObjectName(u"actionSelectAll")
        self.actionDelete = QAction(MainWindowClass)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionSend_Receive_Settings = QAction(MainWindowClass)
        self.actionSend_Receive_Settings.setObjectName(u"actionSend_Receive_Settings")
        self.actionMessage_Settings = QAction(MainWindowClass)
        self.actionMessage_Settings.setObjectName(u"actionMessage_Settings")
        self.actionReport_Settings = QAction(MainWindowClass)
        self.actionReport_Settings.setObjectName(u"actionReport_Settings")
        self.actionLog_Settings = QAction(MainWindowClass)
        self.actionLog_Settings.setObjectName(u"actionLog_Settings")
        self.actionGeneral_Settings = QAction(MainWindowClass)
        self.actionGeneral_Settings.setObjectName(u"actionGeneral_Settings")
        self.actionRun_at_Startup_Settings = QAction(MainWindowClass)
        self.actionRun_at_Startup_Settings.setObjectName(u"actionRun_at_Startup_Settings")
        self.actionScript_Settings = QAction(MainWindowClass)
        self.actionScript_Settings.setObjectName(u"actionScript_Settings")
        self.actionScripting_Tool = QAction(MainWindowClass)
        self.actionScripting_Tool.setObjectName(u"actionScripting_Tool")
        self.actionPick_and_Run_a_Script = QAction(MainWindowClass)
        self.actionPick_and_Run_a_Script.setObjectName(u"actionPick_and_Run_a_Script")
        self.actionPsclet_Session_Counter_Reset = QAction(MainWindowClass)
        self.actionPsclet_Session_Counter_Reset.setObjectName(u"actionPsclet_Session_Counter_Reset")
        self.actionReset_Column_Widths = QAction(MainWindowClass)
        self.actionReset_Column_Widths.setObjectName(u"actionReset_Column_Widths")
        self.actionPack_Column_Widths = QAction(MainWindowClass)
        self.actionPack_Column_Widths.setObjectName(u"actionPack_Column_Widths")
        self.actionReset_Form_to_Normal = QAction(MainWindowClass)
        self.actionReset_Form_to_Normal.setObjectName(u"actionReset_Form_to_Normal")
        self.actionSerial_Com_Port = QAction(MainWindowClass)
        self.actionSerial_Com_Port.setObjectName(u"actionSerial_Com_Port")
        self.actionAGW_Packet_Engine = QAction(MainWindowClass)
        self.actionAGW_Packet_Engine.setObjectName(u"actionAGW_Packet_Engine")
        self.actionTelnet = QAction(MainWindowClass)
        self.actionTelnet.setObjectName(u"actionTelnet")
        self.actionSend_Receive = QAction(MainWindowClass)
        self.actionSend_Receive.setObjectName(u"actionSend_Receive")
        self.actionSend_Receive_No_Bulletins = QAction(MainWindowClass)
        self.actionSend_Receive_No_Bulletins.setObjectName(u"actionSend_Receive_No_Bulletins")
        self.actionSend_Only = QAction(MainWindowClass)
        self.actionSend_Only.setObjectName(u"actionSend_Only")
        self.actionReceive_Only = QAction(MainWindowClass)
        self.actionReceive_Only.setObjectName(u"actionReceive_Only")
        self.actionSet_to_Unread = QAction(MainWindowClass)
        self.actionSet_to_Unread.setObjectName(u"actionSet_to_Unread")
        self.actionSet_to_Read = QAction(MainWindowClass)
        self.actionSet_to_Read.setObjectName(u"actionSet_to_Read")
        self.actionNew_Message_2 = QAction(MainWindowClass)
        self.actionNew_Message_2.setObjectName(u"actionNew_Message_2")
        self.actionOoen_a_Message = QAction(MainWindowClass)
        self.actionOoen_a_Message.setObjectName(u"actionOoen_a_Message")
        self.actionOpen_Enhanced_Message_in_Client = QAction(MainWindowClass)
        self.actionOpen_Enhanced_Message_in_Client.setObjectName(u"actionOpen_Enhanced_Message_in_Client")
        self.actionOpen_Enhanced_Message_as_Text = QAction(MainWindowClass)
        self.actionOpen_Enhanced_Message_as_Text.setObjectName(u"actionOpen_Enhanced_Message_as_Text")
        self.actionForce_One_Time_Bulletin_Retreive = QAction(MainWindowClass)
        self.actionForce_One_Time_Bulletin_Retreive.setObjectName(u"actionForce_One_Time_Bulletin_Retreive")
        self.actionForce_One_Time_Bulletin_Retreive.setEnabled(False)
        self.actionView_Data_Directories = QAction(MainWindowClass)
        self.actionView_Data_Directories.setObjectName(u"actionView_Data_Directories")
        self.actionView_Data_Directories.setEnabled(False)
        self.actionSearch = QAction(MainWindowClass)
        self.actionSearch.setObjectName(u"actionSearch")
        self.action_User_QuickStart = QAction(MainWindowClass)
        self.action_User_QuickStart.setObjectName(u"action_User_QuickStart")
        self.action_User_QuickStart.setEnabled(False)
        self.action_User_Basics = QAction(MainWindowClass)
        self.action_User_Basics.setObjectName(u"action_User_Basics")
        self.action_User_Basics.setEnabled(False)
        self.action_Scripting = QAction(MainWindowClass)
        self.action_Scripting.setObjectName(u"action_Scripting")
        self.action_Scripting.setEnabled(False)
        self.action_ICS213_Messaging_User_Guide = QAction(MainWindowClass)
        self.action_ICS213_Messaging_User_Guide.setObjectName(u"action_ICS213_Messaging_User_Guide")
        self.action_ICS213_Messaging_User_Guide.setEnabled(False)
        self.actionMy_IP_Address = QAction(MainWindowClass)
        self.actionMy_IP_Address.setObjectName(u"actionMy_IP_Address")
        self.actionAbout_OpenPMM = QAction(MainWindowClass)
        self.actionAbout_OpenPMM.setObjectName(u"actionAbout_OpenPMM")
        self.actionReset_all_to_SCC_standard = QAction(MainWindowClass)
        self.actionReset_all_to_SCC_standard.setObjectName(u"actionReset_all_to_SCC_standard")
        self.actionIn_Tray = QAction(MainWindowClass)
        self.actionIn_Tray.setObjectName(u"actionIn_Tray")
        self.actionOut_Tray = QAction(MainWindowClass)
        self.actionOut_Tray.setObjectName(u"actionOut_Tray")
        self.actionIn_Tray_2 = QAction(MainWindowClass)
        self.actionIn_Tray_2.setObjectName(u"actionIn_Tray_2")
        self.actionOut_Tray_2 = QAction(MainWindowClass)
        self.actionOut_Tray_2.setObjectName(u"actionOut_Tray_2")
        self.actionXSC_ICS_213_Message = QAction(MainWindowClass)
        self.actionXSC_ICS_213_Message.setObjectName(u"actionXSC_ICS_213_Message")
        self.actionXSC_Damage_Assessment = QAction(MainWindowClass)
        self.actionXSC_Damage_Assessment.setObjectName(u"actionXSC_Damage_Assessment")
        self.actionXSC_Check_In_Out_Message = QAction(MainWindowClass)
        self.actionXSC_Check_In_Out_Message.setObjectName(u"actionXSC_Check_In_Out_Message")
        self.actionICS_309_Communications_Log = QAction(MainWindowClass)
        self.actionICS_309_Communications_Log.setObjectName(u"actionICS_309_Communications_Log")
        self.centralwidget = QWidget(MainWindowClass)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cNew = QPushButton(self.centralwidget)
        self.cNew.setObjectName(u"cNew")
        self.cNew.setGeometry(QRect(10, 10, 90, 30))
        self.cOpen = QPushButton(self.centralwidget)
        self.cOpen.setObjectName(u"cOpen")
        self.cOpen.setGeometry(QRect(110, 10, 90, 30))
        self.cArchive = QPushButton(self.centralwidget)
        self.cArchive.setObjectName(u"cArchive")
        self.cArchive.setGeometry(QRect(220, 10, 90, 30))
        self.cDelete = QPushButton(self.centralwidget)
        self.cDelete.setObjectName(u"cDelete")
        self.cDelete.setGeometry(QRect(320, 10, 90, 30))
        self.cPrint = QPushButton(self.centralwidget)
        self.cPrint.setObjectName(u"cPrint")
        self.cPrint.setGeometry(QRect(420, 10, 90, 30))
        self.cSendReceive = QPushButton(self.centralwidget)
        self.cSendReceive.setObjectName(u"cSendReceive")
        self.cSendReceive.setGeometry(QRect(625, 10, 130, 30))
        self.cProfile = QComboBox(self.centralwidget)
        self.cProfile.setObjectName(u"cProfile")
        self.cProfile.setGeometry(QRect(1055, 10, 196, 26))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(985, 10, 66, 30))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 60, 140, 481))
        self.cInTray = QPushButton(self.groupBox)
        self.cInTray.setObjectName(u"cInTray")
        self.cInTray.setGeometry(QRect(10, 30, 120, 26))
        self.cInTray.setCheckable(True)
        self.cInTray.setChecked(True)
        self.cInTray.setAutoExclusive(True)
        self.cOutTray = QPushButton(self.groupBox)
        self.cOutTray.setObjectName(u"cOutTray")
        self.cOutTray.setGeometry(QRect(10, 60, 120, 26))
        self.cOutTray.setCheckable(True)
        self.cOutTray.setAutoExclusive(True)
        self.cSentMessages = QPushButton(self.groupBox)
        self.cSentMessages.setObjectName(u"cSentMessages")
        self.cSentMessages.setGeometry(QRect(10, 90, 120, 26))
        self.cSentMessages.setCheckable(True)
        self.cSentMessages.setAutoExclusive(True)
        self.cArchived = QPushButton(self.groupBox)
        self.cArchived.setObjectName(u"cArchived")
        self.cArchived.setGeometry(QRect(10, 120, 120, 26))
        self.cArchived.setCheckable(True)
        self.cArchived.setAutoExclusive(True)
        self.cDrafMessages = QPushButton(self.groupBox)
        self.cDrafMessages.setObjectName(u"cDrafMessages")
        self.cDrafMessages.setGeometry(QRect(10, 150, 120, 26))
        self.cDrafMessages.setCheckable(True)
        self.cDrafMessages.setAutoExclusive(True)
        self.cDeleted = QPushButton(self.groupBox)
        self.cDeleted.setObjectName(u"cDeleted")
        self.cDeleted.setGeometry(QRect(10, 180, 120, 26))
        self.cDeleted.setCheckable(True)
        self.cDeleted.setAutoExclusive(True)
        self.cFolder1 = QPushButton(self.groupBox)
        self.cFolder1.setObjectName(u"cFolder1")
        self.cFolder1.setGeometry(QRect(10, 230, 120, 36))
        self.cFolder1.setCheckable(True)
        self.cFolder1.setAutoExclusive(True)
        self.cFolder2 = QPushButton(self.groupBox)
        self.cFolder2.setObjectName(u"cFolder2")
        self.cFolder2.setGeometry(QRect(10, 270, 120, 36))
        self.cFolder2.setCheckable(True)
        self.cFolder2.setAutoExclusive(True)
        self.cFolder3 = QPushButton(self.groupBox)
        self.cFolder3.setObjectName(u"cFolder3")
        self.cFolder3.setGeometry(QRect(10, 310, 120, 36))
        self.cFolder3.setCheckable(True)
        self.cFolder3.setAutoExclusive(True)
        self.cFolder4 = QPushButton(self.groupBox)
        self.cFolder4.setObjectName(u"cFolder4")
        self.cFolder4.setGeometry(QRect(10, 350, 120, 36))
        self.cFolder4.setCheckable(True)
        self.cFolder4.setAutoExclusive(True)
        self.cFolder5 = QPushButton(self.groupBox)
        self.cFolder5.setObjectName(u"cFolder5")
        self.cFolder5.setGeometry(QRect(10, 390, 120, 36))
        self.cFolder5.setCheckable(True)
        self.cFolder5.setAutoExclusive(True)
        self.cFolderSearchResults = QPushButton(self.groupBox)
        self.cFolderSearchResults.setObjectName(u"cFolderSearchResults")
        self.cFolderSearchResults.setEnabled(True)
        self.cFolderSearchResults.setGeometry(QRect(10, 430, 120, 36))
        self.cFolderSearchResults.setCheckable(True)
        self.cFolderSearchResults.setAutoExclusive(True)
        self.cMailList = QTableWidget(self.centralwidget)
        if (self.cMailList.columnCount() < 9):
            self.cMailList.setColumnCount(9)
        __qtablewidgetitem = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.cMailList.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        self.cMailList.setObjectName(u"cMailList")
        self.cMailList.setGeometry(QRect(190, 65, 1070, 500))
        self.cMailList.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.cMailList.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.cMailList.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.cMailList.setWordWrap(False)
        self.cMailList.horizontalHeader().setStretchLastSection(True)
        self.cMailList.verticalHeader().setVisible(False)
        self.cSendOnly = QPushButton(self.centralwidget)
        self.cSendOnly.setObjectName(u"cSendOnly")
        self.cSendOnly.setGeometry(QRect(760, 10, 100, 30))
        self.cReceiveOnly = QPushButton(self.centralwidget)
        self.cReceiveOnly.setObjectName(u"cReceiveOnly")
        self.cReceiveOnly.setGeometry(QRect(865, 10, 100, 30))
        self.cSearch = QPushButton(self.centralwidget)
        self.cSearch.setObjectName(u"cSearch")
        self.cSearch.setGeometry(QRect(520, 10, 90, 30))
        MainWindowClass.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindowClass)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1276, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuMove_to_Folder = QMenu(self.menuFile)
        self.menuMove_to_Folder.setObjectName(u"menuMove_to_Folder")
        self.menuCopy_to_Folder = QMenu(self.menuFile)
        self.menuCopy_to_Folder.setObjectName(u"menuCopy_to_Folder")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSetup = QMenu(self.menubar)
        self.menuSetup.setObjectName(u"menuSetup")
        self.menuProfiles = QMenu(self.menuSetup)
        self.menuProfiles.setObjectName(u"menuProfiles")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuScripts = QMenu(self.menuTools)
        self.menuScripts.setObjectName(u"menuScripts")
        self.menuInteractive_Packet = QMenu(self.menuTools)
        self.menuInteractive_Packet.setObjectName(u"menuInteractive_Packet")
        self.menuForms = QMenu(self.menubar)
        self.menuForms.setObjectName(u"menuForms")
        self.menuActions = QMenu(self.menubar)
        self.menuActions.setObjectName(u"menuActions")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindowClass.setMenuBar(self.menubar)
        self.cStatusBar = QStatusBar(MainWindowClass)
        self.cStatusBar.setObjectName(u"cStatusBar")
        MainWindowClass.setStatusBar(self.cStatusBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuForms.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_Message)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_As_No_Headers)
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.menuMove_to_Folder.menuAction())
        self.menuFile.addAction(self.menuCopy_to_Folder.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete_All_Messages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_No_Headers)
        self.menuFile.addAction(self.actionPrint_Setup)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuMove_to_Folder.addAction(self.actionIn_Tray)
        self.menuMove_to_Folder.addAction(self.actionOut_Tray)
        self.menuCopy_to_Folder.addAction(self.actionIn_Tray_2)
        self.menuCopy_to_Folder.addAction(self.actionOut_Tray_2)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete)
        self.menuSetup.addAction(self.actionBBS)
        self.menuSetup.addAction(self.actionInterface)
        self.menuSetup.addAction(self.actionStation_ID)
        self.menuSetup.addAction(self.mSetupAddress_Book)
        self.menuSetup.addAction(self.menuProfiles.menuAction())
        self.menuSetup.addAction(self.actionComputer_Time_Check)
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.actionReset_all_to_SCC_standard)
        self.menuProfiles.addAction(self.actionNewProfile)
        self.menuProfiles.addAction(self.actionSaveProfile)
        self.menuProfiles.addAction(self.actionDeleteProfile)
        self.menuTools.addAction(self.actionSend_Receive_Settings)
        self.menuTools.addAction(self.actionMessage_Settings)
        self.menuTools.addAction(self.actionReport_Settings)
        self.menuTools.addAction(self.actionLog_Settings)
        self.menuTools.addAction(self.actionGeneral_Settings)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionRun_at_Startup_Settings)
        self.menuTools.addAction(self.actionScript_Settings)
        self.menuTools.addAction(self.menuScripts.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPsclet_Session_Counter_Reset)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionReset_Column_Widths)
        self.menuTools.addAction(self.actionPack_Column_Widths)
        self.menuTools.addAction(self.actionReset_Form_to_Normal)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuInteractive_Packet.menuAction())
        self.menuScripts.addAction(self.actionScripting_Tool)
        self.menuScripts.addAction(self.actionPick_and_Run_a_Script)
        self.menuInteractive_Packet.addAction(self.actionSerial_Com_Port)
        self.menuInteractive_Packet.addAction(self.actionAGW_Packet_Engine)
        self.menuInteractive_Packet.addAction(self.actionTelnet)
        self.menuForms.addAction(self.actionICS_309_Communications_Log)
        self.menuForms.addSeparator()
        self.menuActions.addAction(self.actionSearch)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionSend_Receive)
        self.menuActions.addAction(self.actionSend_Receive_No_Bulletins)
        self.menuActions.addAction(self.actionSend_Only)
        self.menuActions.addAction(self.actionReceive_Only)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionSet_to_Unread)
        self.menuActions.addAction(self.actionSet_to_Read)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionNew_Message_2)
        self.menuActions.addAction(self.actionOoen_a_Message)
        self.menuActions.addAction(self.actionOpen_Enhanced_Message_in_Client)
        self.menuActions.addAction(self.actionOpen_Enhanced_Message_as_Text)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionForce_One_Time_Bulletin_Retreive)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionView_Data_Directories)
        self.menuActions.addSeparator()
        self.menuHelp.addAction(self.action_User_QuickStart)
        self.menuHelp.addAction(self.action_User_Basics)
        self.menuHelp.addAction(self.action_Scripting)
        self.menuHelp.addAction(self.action_ICS213_Messaging_User_Guide)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_OpenPMM)

        self.retranslateUi(MainWindowClass)
    # setupUi

    def retranslateUi(self, MainWindowClass):
        MainWindowClass.setWindowTitle(QCoreApplication.translate("MainWindowClass", u"OpenPMM", None))
        self.actionBBS.setText(QCoreApplication.translate("MainWindowClass", u"BBS...", None))
        self.actionInterface.setText(QCoreApplication.translate("MainWindowClass", u"Interface...", None))
        self.actionStation_ID.setText(QCoreApplication.translate("MainWindowClass", u"Station ID...", None))
#if QT_CONFIG(shortcut)
        self.actionStation_ID.setShortcut(QCoreApplication.translate("MainWindowClass", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.mSetupAddress_Book.setText(QCoreApplication.translate("MainWindowClass", u"Address Book...", None))
        self.actionComputer_Time_Check.setText(QCoreApplication.translate("MainWindowClass", u"Computer Time Check", None))
        self.actionNewProfile.setText(QCoreApplication.translate("MainWindowClass", u"New...", None))
        self.actionSaveProfile.setText(QCoreApplication.translate("MainWindowClass", u"Save", None))
        self.actionDeleteProfile.setText(QCoreApplication.translate("MainWindowClass", u"Delete...", None))
        self.actionNew_Message.setText(QCoreApplication.translate("MainWindowClass", u"New Message", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindowClass", u"Save As...", None))
        self.actionSave_As_No_Headers.setText(QCoreApplication.translate("MainWindowClass", u"Save As, No Headers...", None))
        self.actionSave_All.setText(QCoreApplication.translate("MainWindowClass", u"Save All...", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindowClass", u"Export", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindowClass", u"Import...", None))
        self.actionDelete_All_Messages.setText(QCoreApplication.translate("MainWindowClass", u"Delete All Messages", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindowClass", u"Print...", None))
        self.actionPrint_No_Headers.setText(QCoreApplication.translate("MainWindowClass", u"Print, No Headers...", None))
        self.actionPrint_Setup.setText(QCoreApplication.translate("MainWindowClass", u"Print Setup...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindowClass", u"Exit", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindowClass", u"Copy", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindowClass", u"Cut", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindowClass", u"Paste", None))
        self.actionSelectAll.setText(QCoreApplication.translate("MainWindowClass", u"SelectAll", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindowClass", u"Delete", None))
        self.actionSend_Receive_Settings.setText(QCoreApplication.translate("MainWindowClass", u"Send/Receive Settings...", None))
        self.actionMessage_Settings.setText(QCoreApplication.translate("MainWindowClass", u"Message Settings...", None))
        self.actionReport_Settings.setText(QCoreApplication.translate("MainWindowClass", u"Report Settings...", None))
        self.actionLog_Settings.setText(QCoreApplication.translate("MainWindowClass", u"Log Settings...", None))
        self.actionGeneral_Settings.setText(QCoreApplication.translate("MainWindowClass", u"General Settings...", None))
        self.actionRun_at_Startup_Settings.setText(QCoreApplication.translate("MainWindowClass", u"Run at Startup Settings...", None))
        self.actionScript_Settings.setText(QCoreApplication.translate("MainWindowClass", u"Script Settings...", None))
        self.actionScripting_Tool.setText(QCoreApplication.translate("MainWindowClass", u"Scripting Tool", None))
        self.actionPick_and_Run_a_Script.setText(QCoreApplication.translate("MainWindowClass", u"Pick and Run a Script", None))
        self.actionPsclet_Session_Counter_Reset.setText(QCoreApplication.translate("MainWindowClass", u"Packet Session Counter Reset", None))
        self.actionReset_Column_Widths.setText(QCoreApplication.translate("MainWindowClass", u"Reset Column Widths", None))
        self.actionPack_Column_Widths.setText(QCoreApplication.translate("MainWindowClass", u"Pack Column Widths", None))
        self.actionReset_Form_to_Normal.setText(QCoreApplication.translate("MainWindowClass", u"Reset Form to Normal", None))
        self.actionSerial_Com_Port.setText(QCoreApplication.translate("MainWindowClass", u"Serial / Com Port", None))
        self.actionAGW_Packet_Engine.setText(QCoreApplication.translate("MainWindowClass", u"AGW Packet Engine", None))
        self.actionTelnet.setText(QCoreApplication.translate("MainWindowClass", u"Telnet", None))
        self.actionSend_Receive.setText(QCoreApplication.translate("MainWindowClass", u"Send/Receive", None))
        self.actionSend_Receive_No_Bulletins.setText(QCoreApplication.translate("MainWindowClass", u"Send/Receive, No Bulletins", None))
        self.actionSend_Only.setText(QCoreApplication.translate("MainWindowClass", u"Send Only", None))
        self.actionReceive_Only.setText(QCoreApplication.translate("MainWindowClass", u"Receive Only", None))
        self.actionSet_to_Unread.setText(QCoreApplication.translate("MainWindowClass", u"Set to Unread", None))
        self.actionSet_to_Read.setText(QCoreApplication.translate("MainWindowClass", u"Set to Read", None))
        self.actionNew_Message_2.setText(QCoreApplication.translate("MainWindowClass", u"New Message", None))
        self.actionOoen_a_Message.setText(QCoreApplication.translate("MainWindowClass", u"Open a Message", None))
        self.actionOpen_Enhanced_Message_in_Client.setText(QCoreApplication.translate("MainWindowClass", u"Open Enhanced Message in Client", None))
        self.actionOpen_Enhanced_Message_as_Text.setText(QCoreApplication.translate("MainWindowClass", u"Open Enhanced Message as Text", None))
        self.actionForce_One_Time_Bulletin_Retreive.setText(QCoreApplication.translate("MainWindowClass", u"Force One-Time Bulletin Retreive", None))
        self.actionView_Data_Directories.setText(QCoreApplication.translate("MainWindowClass", u"View Data Directories", None))
        self.actionSearch.setText(QCoreApplication.translate("MainWindowClass", u"Search", None))
        self.action_User_QuickStart.setText(QCoreApplication.translate("MainWindowClass", u"User QuickStart", None))
        self.action_User_Basics.setText(QCoreApplication.translate("MainWindowClass", u"User Basics", None))
        self.action_Scripting.setText(QCoreApplication.translate("MainWindowClass", u"Scripting", None))
        self.action_ICS213_Messaging_User_Guide.setText(QCoreApplication.translate("MainWindowClass", u"ICS213 Messaging User Guide", None))
        self.actionMy_IP_Address.setText(QCoreApplication.translate("MainWindowClass", u"My IP Address", None))
        self.actionAbout_OpenPMM.setText(QCoreApplication.translate("MainWindowClass", u"About OpenPMM", None))
        self.actionReset_all_to_SCC_standard.setText(QCoreApplication.translate("MainWindowClass", u"Reset all to SCC standard", None))
        self.actionIn_Tray.setText(QCoreApplication.translate("MainWindowClass", u"In Tray", None))
        self.actionOut_Tray.setText(QCoreApplication.translate("MainWindowClass", u"Out Tray", None))
        self.actionIn_Tray_2.setText(QCoreApplication.translate("MainWindowClass", u"In Tray", None))
        self.actionOut_Tray_2.setText(QCoreApplication.translate("MainWindowClass", u"Out Tray", None))
        self.actionXSC_ICS_213_Message.setText(QCoreApplication.translate("MainWindowClass", u"XSC ICS-213 Message", None))
        self.actionXSC_Damage_Assessment.setText(QCoreApplication.translate("MainWindowClass", u"XSC Damage Assessment", None))
        self.actionXSC_Check_In_Out_Message.setText(QCoreApplication.translate("MainWindowClass", u"XSC Check-In/Out Message", None))
        self.actionICS_309_Communications_Log.setText(QCoreApplication.translate("MainWindowClass", u"ICS-309 Communications Log", None))
        self.cNew.setText(QCoreApplication.translate("MainWindowClass", u"New", None))
        self.cOpen.setText(QCoreApplication.translate("MainWindowClass", u"Open", None))
        self.cArchive.setText(QCoreApplication.translate("MainWindowClass", u"Archive", None))
        self.cDelete.setText(QCoreApplication.translate("MainWindowClass", u"Delete", None))
        self.cPrint.setText(QCoreApplication.translate("MainWindowClass", u"Print", None))
        self.cSendReceive.setText(QCoreApplication.translate("MainWindowClass", u"Send/Receive", None))
        self.label.setText(QCoreApplication.translate("MainWindowClass", u"Profile:", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindowClass", u"Folder List", None))
        self.cInTray.setText(QCoreApplication.translate("MainWindowClass", u"In Tray", None))
        self.cOutTray.setText(QCoreApplication.translate("MainWindowClass", u"Out Tray", None))
        self.cSentMessages.setText(QCoreApplication.translate("MainWindowClass", u"Sent Messages", None))
        self.cArchived.setText(QCoreApplication.translate("MainWindowClass", u"Archive", None))
        self.cDrafMessages.setText(QCoreApplication.translate("MainWindowClass", u"Draft Messages", None))
        self.cDeleted.setText(QCoreApplication.translate("MainWindowClass", u"Deleted", None))
        self.cFolder1.setText(QCoreApplication.translate("MainWindowClass", u"Folder 1", None))
        self.cFolder2.setText(QCoreApplication.translate("MainWindowClass", u"Folder 2", None))
        self.cFolder3.setText(QCoreApplication.translate("MainWindowClass", u"Folder 3", None))
        self.cFolder4.setText(QCoreApplication.translate("MainWindowClass", u"Folder 4", None))
        self.cFolder5.setText(QCoreApplication.translate("MainWindowClass", u"Folder 5", None))
        self.cFolderSearchResults.setText(QCoreApplication.translate("MainWindowClass", u"Search Results", None))
        ___qtablewidgetitem = self.cMailList.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindowClass", u"U", None));
        ___qtablewidgetitem1 = self.cMailList.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindowClass", u"Type", None));
        ___qtablewidgetitem2 = self.cMailList.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindowClass", u"From", None));
        ___qtablewidgetitem3 = self.cMailList.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindowClass", u"To", None));
        ___qtablewidgetitem4 = self.cMailList.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindowClass", u"BBS", None));
        ___qtablewidgetitem5 = self.cMailList.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindowClass", u"Local ID", None));
        ___qtablewidgetitem6 = self.cMailList.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindowClass", u"Subject", None));
        ___qtablewidgetitem7 = self.cMailList.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindowClass", u"Date/Time", None));
        ___qtablewidgetitem8 = self.cMailList.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindowClass", u"Size", None));
        self.cSendOnly.setText(QCoreApplication.translate("MainWindowClass", u"SendOnly", None))
        self.cReceiveOnly.setText(QCoreApplication.translate("MainWindowClass", u"Receive Only", None))
        self.cSearch.setText(QCoreApplication.translate("MainWindowClass", u"Search", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindowClass", u"File", None))
        self.menuMove_to_Folder.setTitle(QCoreApplication.translate("MainWindowClass", u"Move to Folder", None))
        self.menuCopy_to_Folder.setTitle(QCoreApplication.translate("MainWindowClass", u"Copy to Folder", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindowClass", u"Edit", None))
        self.menuSetup.setTitle(QCoreApplication.translate("MainWindowClass", u"Setup", None))
        self.menuProfiles.setTitle(QCoreApplication.translate("MainWindowClass", u"Profiles", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindowClass", u"Tools", None))
        self.menuScripts.setTitle(QCoreApplication.translate("MainWindowClass", u"Scripts", None))
        self.menuInteractive_Packet.setTitle(QCoreApplication.translate("MainWindowClass", u"Interactive Packet", None))
        self.menuForms.setTitle(QCoreApplication.translate("MainWindowClass", u"Forms", None))
        self.menuActions.setTitle(QCoreApplication.translate("MainWindowClass", u"Actions", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindowClass", u"Help", None))
    # retranslateUi

