# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'newpacketmessage.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_NewPacketMessageClass(object):
    def setupUi(self, NewPacketMessageClass):
        if not NewPacketMessageClass.objectName():
            NewPacketMessageClass.setObjectName(u"NewPacketMessageClass")
        NewPacketMessageClass.resize(733, 651)
        self.actionSend = QAction(NewPacketMessageClass)
        self.actionSend.setObjectName(u"actionSend")
        self.actionSave_As = QAction(NewPacketMessageClass)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As_No_Headers = QAction(NewPacketMessageClass)
        self.actionSave_As_No_Headers.setObjectName(u"actionSave_As_No_Headers")
        self.actionSave_All = QAction(NewPacketMessageClass)
        self.actionSave_All.setObjectName(u"actionSave_All")
        self.actionExport = QAction(NewPacketMessageClass)
        self.actionExport.setObjectName(u"actionExport")
        self.actionOpen_a_File = QAction(NewPacketMessageClass)
        self.actionOpen_a_File.setObjectName(u"actionOpen_a_File")
        self.actionMove_to_Folder = QAction(NewPacketMessageClass)
        self.actionMove_to_Folder.setObjectName(u"actionMove_to_Folder")
        self.actionOpen_a_Report = QAction(NewPacketMessageClass)
        self.actionOpen_a_Report.setObjectName(u"actionOpen_a_Report")
        self.actionSave = QAction(NewPacketMessageClass)
        self.actionSave.setObjectName(u"actionSave")
        self.actionPrint = QAction(NewPacketMessageClass)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionPrint_No_Headers = QAction(NewPacketMessageClass)
        self.actionPrint_No_Headers.setObjectName(u"actionPrint_No_Headers")
        self.actionExit = QAction(NewPacketMessageClass)
        self.actionExit.setObjectName(u"actionExit")
        self.actionNTS_Message_Maker = QAction(NewPacketMessageClass)
        self.actionNTS_Message_Maker.setObjectName(u"actionNTS_Message_Maker")
        self.actionProcess_a_Report = QAction(NewPacketMessageClass)
        self.actionProcess_a_Report.setObjectName(u"actionProcess_a_Report")
        self.actionClear_Remaining_Prompts = QAction(NewPacketMessageClass)
        self.actionClear_Remaining_Prompts.setObjectName(u"actionClear_Remaining_Prompts")
        self.actionClose = QAction(NewPacketMessageClass)
        self.actionClose.setObjectName(u"actionClose")
        self.actionCut = QAction(NewPacketMessageClass)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(NewPacketMessageClass)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(NewPacketMessageClass)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionSelect_All = QAction(NewPacketMessageClass)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionDelete_Message = QAction(NewPacketMessageClass)
        self.actionDelete_Message.setObjectName(u"actionDelete_Message")
        self.actionReply = QAction(NewPacketMessageClass)
        self.actionReply.setObjectName(u"actionReply")
        self.actionForward = QAction(NewPacketMessageClass)
        self.actionForward.setObjectName(u"actionForward")
        self.actionSet_as_a_Private_Message = QAction(NewPacketMessageClass)
        self.actionSet_as_a_Private_Message.setObjectName(u"actionSet_as_a_Private_Message")
        self.actionSet_as_a_NTS_Message = QAction(NewPacketMessageClass)
        self.actionSet_as_a_NTS_Message.setObjectName(u"actionSet_as_a_NTS_Message")
        self.actionSet_as_a_Bulletin = QAction(NewPacketMessageClass)
        self.actionSet_as_a_Bulletin.setObjectName(u"actionSet_as_a_Bulletin")
        self.actionRequest_Delivery_Receipt = QAction(NewPacketMessageClass)
        self.actionRequest_Delivery_Receipt.setObjectName(u"actionRequest_Delivery_Receipt")
        self.actionRequest_Read_Receipt = QAction(NewPacketMessageClass)
        self.actionRequest_Read_Receipt.setObjectName(u"actionRequest_Read_Receipt")
        self.actionKeep_ICS213_Local = QAction(NewPacketMessageClass)
        self.actionKeep_ICS213_Local.setObjectName(u"actionKeep_ICS213_Local")
        self.actionOpen_in_Form = QAction(NewPacketMessageClass)
        self.actionOpen_in_Form.setObjectName(u"actionOpen_in_Form")
        self.actionLine_Draw_toggle = QAction(NewPacketMessageClass)
        self.actionLine_Draw_toggle.setObjectName(u"actionLine_Draw_toggle")
        self.actionFont = QAction(NewPacketMessageClass)
        self.actionFont.setObjectName(u"actionFont")
        self.actionReset_Font_default = QAction(NewPacketMessageClass)
        self.actionReset_Font_default.setObjectName(u"actionReset_Font_default")
        self.actionReset_Form_to_Normal = QAction(NewPacketMessageClass)
        self.actionReset_Form_to_Normal.setObjectName(u"actionReset_Form_to_Normal")
        self.centralWidget = QWidget(NewPacketMessageClass)
        self.centralWidget.setObjectName(u"centralWidget")
        self.label = QLabel(self.centralWidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 45, 60, 22))
        self.cBBS = QLineEdit(self.centralWidget)
        self.cBBS.setObjectName(u"cBBS")
        self.cBBS.setGeometry(QRect(80, 45, 640, 22))
        self.label_2 = QLabel(self.centralWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 60, 22))
        self.cFrom = QLineEdit(self.centralWidget)
        self.cFrom.setObjectName(u"cFrom")
        self.cFrom.setGeometry(QRect(80, 70, 640, 22))
        self.cTo = QLineEdit(self.centralWidget)
        self.cTo.setObjectName(u"cTo")
        self.cTo.setGeometry(QRect(80, 95, 640, 22))
        self.label_4 = QLabel(self.centralWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 120, 60, 22))
        self.cSubject = QLineEdit(self.centralWidget)
        self.cSubject.setObjectName(u"cSubject")
        self.cSubject.setGeometry(QRect(80, 120, 640, 22))
        self.cToHelper = QPushButton(self.centralWidget)
        self.cToHelper.setObjectName(u"cToHelper")
        self.cToHelper.setGeometry(QRect(10, 95, 60, 22))
        self.cSend = QPushButton(self.centralWidget)
        self.cSend.setObjectName(u"cSend")
        self.cSend.setGeometry(QRect(10, 5, 75, 30))
        self.cPrint = QPushButton(self.centralWidget)
        self.cPrint.setObjectName(u"cPrint")
        self.cPrint.setGeometry(QRect(95, 5, 50, 30))
        self.cSave = QPushButton(self.centralWidget)
        self.cSave.setObjectName(u"cSave")
        self.cSave.setGeometry(QRect(145, 5, 50, 30))
        self.cDelete = QPushButton(self.centralWidget)
        self.cDelete.setObjectName(u"cDelete")
        self.cDelete.setGeometry(QRect(195, 5, 50, 30))
        self.cClose = QPushButton(self.centralWidget)
        self.cClose.setObjectName(u"cClose")
        self.cClose.setGeometry(QRect(245, 5, 50, 30))
        self.cUrgent = QPushButton(self.centralWidget)
        self.cUrgent.setObjectName(u"cUrgent")
        self.cUrgent.setGeometry(QRect(380, 5, 60, 30))
        self.cUrgent.setCheckable(True)
        self.cMessageTypePrivate = QPushButton(self.centralWidget)
        self.cMessageTypePrivate.setObjectName(u"cMessageTypePrivate")
        self.cMessageTypePrivate.setGeometry(QRect(485, 5, 55, 30))
        self.cMessageTypePrivate.setCheckable(True)
        self.cMessageTypePrivate.setChecked(True)
        self.cMessageTypePrivate.setAutoExclusive(True)
        self.cMessageTypeBulletin = QPushButton(self.centralWidget)
        self.cMessageTypeBulletin.setObjectName(u"cMessageTypeBulletin")
        self.cMessageTypeBulletin.setGeometry(QRect(540, 5, 55, 30))
        self.cMessageTypeBulletin.setCheckable(True)
        self.cMessageTypeBulletin.setAutoExclusive(True)
        self.cMessageTypeNts = QPushButton(self.centralWidget)
        self.cMessageTypeNts.setObjectName(u"cMessageTypeNts")
        self.cMessageTypeNts.setGeometry(QRect(595, 5, 55, 30))
        self.cMessageTypeNts.setCheckable(True)
        self.cMessageTypeNts.setAutoExclusive(True)
        self.cMessage = QPlainTextEdit(self.centralWidget)
        self.cMessage.setObjectName(u"cMessage")
        self.cMessage.setGeometry(QRect(10, 155, 711, 416))
        NewPacketMessageClass.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(NewPacketMessageClass)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 733, 33))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuActions = QMenu(self.menuBar)
        self.menuActions.setObjectName(u"menuActions")
        self.menuWindow = QMenu(self.menuBar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        NewPacketMessageClass.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(NewPacketMessageClass)
        self.statusBar.setObjectName(u"statusBar")
        NewPacketMessageClass.setStatusBar(self.statusBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuActions.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSend)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_a_File)
        self.menuFile.addAction(self.actionOpen_a_Report)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_As_No_Headers)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNTS_Message_Maker)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionProcess_a_Report)
        self.menuFile.addAction(self.actionClear_Remaining_Prompts)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_No_Headers)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete_Message)
        self.menuActions.addAction(self.actionReply)
        self.menuActions.addAction(self.actionForward)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionSet_as_a_Private_Message)
        self.menuActions.addAction(self.actionSet_as_a_NTS_Message)
        self.menuActions.addAction(self.actionSet_as_a_Bulletin)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionRequest_Delivery_Receipt)
        self.menuActions.addAction(self.actionRequest_Read_Receipt)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionKeep_ICS213_Local)
        self.menuActions.addAction(self.actionOpen_in_Form)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionLine_Draw_toggle)
        self.menuActions.addAction(self.actionFont)
        self.menuActions.addAction(self.actionReset_Font_default)
        self.menuWindow.addAction(self.actionReset_Form_to_Normal)

        self.retranslateUi(NewPacketMessageClass)
    # setupUi

    def retranslateUi(self, NewPacketMessageClass):
        NewPacketMessageClass.setWindowTitle(QCoreApplication.translate("NewPacketMessageClass", u"NewPacketMessage", None))
        self.actionSend.setText(QCoreApplication.translate("NewPacketMessageClass", u"Send", None))
        self.actionSave_As.setText(QCoreApplication.translate("NewPacketMessageClass", u"Save As...", None))
        self.actionSave_As_No_Headers.setText(QCoreApplication.translate("NewPacketMessageClass", u"Save As, No Headers...", None))
        self.actionSave_All.setText(QCoreApplication.translate("NewPacketMessageClass", u"Save All...", None))
        self.actionExport.setText(QCoreApplication.translate("NewPacketMessageClass", u"Export", None))
        self.actionOpen_a_File.setText(QCoreApplication.translate("NewPacketMessageClass", u"Open a FIle", None))
        self.actionMove_to_Folder.setText(QCoreApplication.translate("NewPacketMessageClass", u"Move to Folder...", None))
        self.actionOpen_a_Report.setText(QCoreApplication.translate("NewPacketMessageClass", u"Open a Report", None))
        self.actionSave.setText(QCoreApplication.translate("NewPacketMessageClass", u"Save", None))
        self.actionPrint.setText(QCoreApplication.translate("NewPacketMessageClass", u"Print...", None))
        self.actionPrint_No_Headers.setText(QCoreApplication.translate("NewPacketMessageClass", u"Print, No Headers...", None))
        self.actionExit.setText(QCoreApplication.translate("NewPacketMessageClass", u"Exit", None))
        self.actionNTS_Message_Maker.setText(QCoreApplication.translate("NewPacketMessageClass", u"NTS Message Maker", None))
        self.actionProcess_a_Report.setText(QCoreApplication.translate("NewPacketMessageClass", u"Process a Report", None))
        self.actionClear_Remaining_Prompts.setText(QCoreApplication.translate("NewPacketMessageClass", u"Clear Remaining Prompts", None))
        self.actionClose.setText(QCoreApplication.translate("NewPacketMessageClass", u"Close", None))
        self.actionCut.setText(QCoreApplication.translate("NewPacketMessageClass", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("NewPacketMessageClass", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("NewPacketMessageClass", u"Paste", None))
        self.actionSelect_All.setText(QCoreApplication.translate("NewPacketMessageClass", u"Select All", None))
        self.actionDelete_Message.setText(QCoreApplication.translate("NewPacketMessageClass", u"Delete Message", None))
        self.actionReply.setText(QCoreApplication.translate("NewPacketMessageClass", u"Reply", None))
        self.actionForward.setText(QCoreApplication.translate("NewPacketMessageClass", u"Forward", None))
        self.actionSet_as_a_Private_Message.setText(QCoreApplication.translate("NewPacketMessageClass", u"Set as a Private Message", None))
        self.actionSet_as_a_NTS_Message.setText(QCoreApplication.translate("NewPacketMessageClass", u"Set as a NTS Message", None))
        self.actionSet_as_a_Bulletin.setText(QCoreApplication.translate("NewPacketMessageClass", u"Set as a Bulletin", None))
        self.actionRequest_Delivery_Receipt.setText(QCoreApplication.translate("NewPacketMessageClass", u"Request Delivery Receipt", None))
        self.actionRequest_Read_Receipt.setText(QCoreApplication.translate("NewPacketMessageClass", u"Request Read Receipt", None))
        self.actionKeep_ICS213_Local.setText(QCoreApplication.translate("NewPacketMessageClass", u"Keep ICS213 Local", None))
        self.actionOpen_in_Form.setText(QCoreApplication.translate("NewPacketMessageClass", u"Open in Form", None))
        self.actionLine_Draw_toggle.setText(QCoreApplication.translate("NewPacketMessageClass", u"Line Draw (toggle)", None))
        self.actionFont.setText(QCoreApplication.translate("NewPacketMessageClass", u"Font...", None))
        self.actionReset_Font_default.setText(QCoreApplication.translate("NewPacketMessageClass", u"Reset Font (default)", None))
        self.actionReset_Form_to_Normal.setText(QCoreApplication.translate("NewPacketMessageClass", u"Reset Form to Normal", None))
        self.label.setText(QCoreApplication.translate("NewPacketMessageClass", u"BBS", None))
        self.label_2.setText(QCoreApplication.translate("NewPacketMessageClass", u"From", None))
        self.label_4.setText(QCoreApplication.translate("NewPacketMessageClass", u"Subject", None))
        self.cToHelper.setText(QCoreApplication.translate("NewPacketMessageClass", u"To...", None))
        self.cSend.setText(QCoreApplication.translate("NewPacketMessageClass", u"Send", None))
        self.cPrint.setText(QCoreApplication.translate("NewPacketMessageClass", u"Print", None))
        self.cSave.setText(QCoreApplication.translate("NewPacketMessageClass", u"Save", None))
        self.cDelete.setText(QCoreApplication.translate("NewPacketMessageClass", u"Delete", None))
        self.cClose.setText(QCoreApplication.translate("NewPacketMessageClass", u"Close", None))
        self.cUrgent.setText(QCoreApplication.translate("NewPacketMessageClass", u"Urgent", None))
        self.cMessageTypePrivate.setText(QCoreApplication.translate("NewPacketMessageClass", u"Private", None))
        self.cMessageTypeBulletin.setText(QCoreApplication.translate("NewPacketMessageClass", u"Bulletin", None))
        self.cMessageTypeNts.setText(QCoreApplication.translate("NewPacketMessageClass", u"NTS", None))
        self.menuFile.setTitle(QCoreApplication.translate("NewPacketMessageClass", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("NewPacketMessageClass", u"Edit", None))
        self.menuActions.setTitle(QCoreApplication.translate("NewPacketMessageClass", u"Actions", None))
        self.menuWindow.setTitle(QCoreApplication.translate("NewPacketMessageClass", u"Window", None))
        self.menuHelp.setTitle(QCoreApplication.translate("NewPacketMessageClass", u"Help", None))
    # retranslateUi

