# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'readmessagedialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QLabel, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_ReadMessageDialogClass(object):
    def setupUi(self, ReadMessageDialogClass):
        if not ReadMessageDialogClass.objectName():
            ReadMessageDialogClass.setObjectName(u"ReadMessageDialogClass")
        ReadMessageDialogClass.resize(638, 560)
        self.actionSend = QAction(ReadMessageDialogClass)
        self.actionSend.setObjectName(u"actionSend")
        self.actionOpen = QAction(ReadMessageDialogClass)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(ReadMessageDialogClass)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(ReadMessageDialogClass)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As_No_Headers = QAction(ReadMessageDialogClass)
        self.actionSave_As_No_Headers.setObjectName(u"actionSave_As_No_Headers")
        self.actionPrint = QAction(ReadMessageDialogClass)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionPrint_No_Headers = QAction(ReadMessageDialogClass)
        self.actionPrint_No_Headers.setObjectName(u"actionPrint_No_Headers")
        self.actionClose = QAction(ReadMessageDialogClass)
        self.actionClose.setObjectName(u"actionClose")
        self.actionCut = QAction(ReadMessageDialogClass)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(ReadMessageDialogClass)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(ReadMessageDialogClass)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionSelect_All = QAction(ReadMessageDialogClass)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionDelete_Message = QAction(ReadMessageDialogClass)
        self.actionDelete_Message.setObjectName(u"actionDelete_Message")
        self.actionPacket_Header = QAction(ReadMessageDialogClass)
        self.actionPacket_Header.setObjectName(u"actionPacket_Header")
        self.actionJNOS_Line_Fix_BETA = QAction(ReadMessageDialogClass)
        self.actionJNOS_Line_Fix_BETA.setObjectName(u"actionJNOS_Line_Fix_BETA")
        self.actionReply = QAction(ReadMessageDialogClass)
        self.actionReply.setObjectName(u"actionReply")
        self.actionReply_to_All = QAction(ReadMessageDialogClass)
        self.actionReply_to_All.setObjectName(u"actionReply_to_All")
        self.actionForward = QAction(ReadMessageDialogClass)
        self.actionForward.setObjectName(u"actionForward")
        self.actionSet_to_Unread = QAction(ReadMessageDialogClass)
        self.actionSet_to_Unread.setObjectName(u"actionSet_to_Unread")
        self.actionResend = QAction(ReadMessageDialogClass)
        self.actionResend.setObjectName(u"actionResend")
        self.actionAdd_Address = QAction(ReadMessageDialogClass)
        self.actionAdd_Address.setObjectName(u"actionAdd_Address")
        self.actionChange_Route = QAction(ReadMessageDialogClass)
        self.actionChange_Route.setObjectName(u"actionChange_Route")
        self.actionCopy_to_ICS213mm_Format = QAction(ReadMessageDialogClass)
        self.actionCopy_to_ICS213mm_Format.setObjectName(u"actionCopy_to_ICS213mm_Format")
        self.actionOpen_in_Form = QAction(ReadMessageDialogClass)
        self.actionOpen_in_Form.setObjectName(u"actionOpen_in_Form")
        self.actionLine_Draw_toggle = QAction(ReadMessageDialogClass)
        self.actionLine_Draw_toggle.setObjectName(u"actionLine_Draw_toggle")
        self.actionFont = QAction(ReadMessageDialogClass)
        self.actionFont.setObjectName(u"actionFont")
        self.actionReset_Font_default = QAction(ReadMessageDialogClass)
        self.actionReset_Font_default.setObjectName(u"actionReset_Font_default")
        self.actionReset_Form_to_Normal = QAction(ReadMessageDialogClass)
        self.actionReset_Form_to_Normal.setObjectName(u"actionReset_Form_to_Normal")
        self.centralWidget = QWidget(ReadMessageDialogClass)
        self.centralWidget.setObjectName(u"centralWidget")
        self.c_message_body = QPlainTextEdit(self.centralWidget)
        self.c_message_body.setObjectName(u"c_message_body")
        self.c_message_body.setGeometry(QRect(5, 130, 625, 365))
        self.c_message_body.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.label = QLabel(self.centralWidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 45, 90, 16))
        self.c_bbs = QLabel(self.centralWidget)
        self.c_bbs.setObjectName(u"c_bbs")
        self.c_bbs.setGeometry(QRect(100, 45, 200, 16))
        font = QFont()
        font.setBold(True)
        self.c_bbs.setFont(font)
        self.label_3 = QLabel(self.centralWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 65, 90, 16))
        self.c_from = QLabel(self.centralWidget)
        self.c_from.setObjectName(u"c_from")
        self.c_from.setGeometry(QRect(100, 65, 200, 16))
        self.c_from.setFont(font)
        self.label_5 = QLabel(self.centralWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 85, 90, 16))
        self.c_to = QLabel(self.centralWidget)
        self.c_to.setObjectName(u"c_to")
        self.c_to.setGeometry(QRect(100, 85, 200, 16))
        self.c_to.setFont(font)
        self.label_7 = QLabel(self.centralWidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 105, 90, 16))
        self.c_subject = QLabel(self.centralWidget)
        self.c_subject.setObjectName(u"c_subject")
        self.c_subject.setGeometry(QRect(100, 105, 525, 16))
        self.c_subject.setFont(font)
        self.label_9 = QLabel(self.centralWidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(315, 45, 125, 16))
        self.c_received = QLabel(self.centralWidget)
        self.c_received.setObjectName(u"c_received")
        self.c_received.setGeometry(QRect(440, 45, 185, 16))
        self.c_received.setFont(font)
        self.c_sent = QLabel(self.centralWidget)
        self.c_sent.setObjectName(u"c_sent")
        self.c_sent.setGeometry(QRect(440, 65, 185, 16))
        self.c_sent.setFont(font)
        self.label_12 = QLabel(self.centralWidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(315, 65, 125, 16))
        self.pushButton = QPushButton(self.centralWidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QRect(10, 10, 75, 30))
        self.pushButton_2 = QPushButton(self.centralWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QRect(85, 10, 75, 30))
        self.pushButton_3 = QPushButton(self.centralWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QRect(160, 10, 100, 30))
        self.pushButton_4 = QPushButton(self.centralWidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QRect(260, 10, 75, 30))
        self.pushButton_5 = QPushButton(self.centralWidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QRect(350, 10, 75, 30))
        self.pushButton_6 = QPushButton(self.centralWidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QRect(425, 10, 75, 30))
        self.pushButton_7 = QPushButton(self.centralWidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QRect(500, 10, 75, 30))
        self.c_local_id = QLabel(self.centralWidget)
        self.c_local_id.setObjectName(u"c_local_id")
        self.c_local_id.setGeometry(QRect(440, 85, 185, 16))
        self.c_local_id.setFont(font)
        self.label_13 = QLabel(self.centralWidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(315, 85, 125, 16))
        ReadMessageDialogClass.setCentralWidget(self.centralWidget)
        self.statusBar = QStatusBar(ReadMessageDialogClass)
        self.statusBar.setObjectName(u"statusBar")
        ReadMessageDialogClass.setStatusBar(self.statusBar)
        self.menuBar = QMenuBar(ReadMessageDialogClass)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 638, 33))
        self.menuPrint = QMenu(self.menuBar)
        self.menuPrint.setObjectName(u"menuPrint")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuAction = QMenu(self.menuBar)
        self.menuAction.setObjectName(u"menuAction")
        self.menuWindows = QMenu(self.menuBar)
        self.menuWindows.setObjectName(u"menuWindows")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        ReadMessageDialogClass.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuPrint.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuAction.menuAction())
        self.menuBar.addAction(self.menuWindows.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuPrint.addAction(self.actionSend)
        self.menuPrint.addSeparator()
        self.menuPrint.addAction(self.actionOpen)
        self.menuPrint.addAction(self.actionSave)
        self.menuPrint.addAction(self.actionSave_As)
        self.menuPrint.addAction(self.actionSave_As_No_Headers)
        self.menuPrint.addSeparator()
        self.menuPrint.addAction(self.actionPrint)
        self.menuPrint.addAction(self.actionPrint_No_Headers)
        self.menuPrint.addSeparator()
        self.menuPrint.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete_Message)
        self.menuView.addAction(self.actionPacket_Header)
        self.menuView.addAction(self.actionJNOS_Line_Fix_BETA)
        self.menuAction.addAction(self.actionReply)
        self.menuAction.addAction(self.actionReply_to_All)
        self.menuAction.addAction(self.actionForward)
        self.menuAction.addAction(self.actionSet_to_Unread)
        self.menuAction.addAction(self.actionResend)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionAdd_Address)
        self.menuAction.addAction(self.actionChange_Route)
        self.menuAction.addAction(self.actionCopy_to_ICS213mm_Format)
        self.menuAction.addAction(self.actionOpen_in_Form)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionLine_Draw_toggle)
        self.menuAction.addAction(self.actionFont)
        self.menuAction.addAction(self.actionReset_Font_default)
        self.menuWindows.addAction(self.actionReset_Form_to_Normal)

        self.retranslateUi(ReadMessageDialogClass)

        QMetaObject.connectSlotsByName(ReadMessageDialogClass)
    # setupUi

    def retranslateUi(self, ReadMessageDialogClass):
        ReadMessageDialogClass.setWindowTitle(QCoreApplication.translate("ReadMessageDialogClass", u"Read Message", None))
        self.actionSend.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Send", None))
        self.actionOpen.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Save As,,,", None))
        self.actionSave_As_No_Headers.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Save As, No Headers...", None))
        self.actionPrint.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Print...", None))
        self.actionPrint_No_Headers.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Print, No Headers...", None))
        self.actionClose.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Close", None))
        self.actionCut.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Paste", None))
        self.actionSelect_All.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Select All", None))
        self.actionDelete_Message.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Delete Message", None))
        self.actionPacket_Header.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Packet Header", None))
        self.actionJNOS_Line_Fix_BETA.setText(QCoreApplication.translate("ReadMessageDialogClass", u"JNOS Line Fix (BETA)", None))
        self.actionReply.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Reply", None))
        self.actionReply_to_All.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Reply to All", None))
        self.actionForward.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Forward", None))
        self.actionSet_to_Unread.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Set to Unread", None))
        self.actionResend.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Resend...", None))
        self.actionAdd_Address.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Add Address...", None))
        self.actionChange_Route.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Change Route...", None))
        self.actionCopy_to_ICS213mm_Format.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Copy to ICS213mm Format", None))
        self.actionOpen_in_Form.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Open in Form", None))
        self.actionLine_Draw_toggle.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Line Draw (toggle)", None))
        self.actionFont.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Font...", None))
        self.actionReset_Font_default.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Reset Font (default)", None))
        self.actionReset_Form_to_Normal.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Reset Form to Normal", None))
        self.label.setText(QCoreApplication.translate("ReadMessageDialogClass", u"BBS", None))
        self.c_bbs.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.label_3.setText(QCoreApplication.translate("ReadMessageDialogClass", u"From", None))
        self.c_from.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.label_5.setText(QCoreApplication.translate("ReadMessageDialogClass", u"To", None))
        self.c_to.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.label_7.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Subject", None))
        self.c_subject.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.label_9.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Received", None))
        self.c_received.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.c_sent.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.label_12.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Sent", None))
        self.pushButton.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Print", None))
        self.pushButton_2.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Reply", None))
        self.pushButton_3.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Reply to All", None))
        self.pushButton_4.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Forward", None))
        self.pushButton_5.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Archive", None))
        self.pushButton_6.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Delete", None))
        self.pushButton_7.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Close", None))
        self.c_local_id.setText(QCoreApplication.translate("ReadMessageDialogClass", u"TextLabel", None))
        self.label_13.setText(QCoreApplication.translate("ReadMessageDialogClass", u"Local message ID", None))
        self.menuPrint.setTitle(QCoreApplication.translate("ReadMessageDialogClass", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("ReadMessageDialogClass", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("ReadMessageDialogClass", u"View", None))
        self.menuAction.setTitle(QCoreApplication.translate("ReadMessageDialogClass", u"Action", None))
        self.menuWindows.setTitle(QCoreApplication.translate("ReadMessageDialogClass", u"Windows", None))
        self.menuHelp.setTitle(QCoreApplication.translate("ReadMessageDialogClass", u"Help", None))
    # retranslateUi

