# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'reportsettingsdialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGroupBox, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_ReportSettingsDialogClass(object):
    def setupUi(self, ReportSettingsDialogClass):
        if not ReportSettingsDialogClass.objectName():
            ReportSettingsDialogClass.setObjectName(u"ReportSettingsDialogClass")
        ReportSettingsDialogClass.resize(490, 430)
        self.tabWidget = QTabWidget(ReportSettingsDialogClass)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(5, 5, 480, 380))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 450, 71))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 110, 16))
        self.cNextMessage = QLineEdit(self.groupBox)
        self.cNextMessage.setObjectName(u"cNextMessage")
        self.cNextMessage.setGeometry(QRect(120, 25, 200, 22))
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 90, 450, 260))
        self.cOrganization = QLineEdit(self.groupBox_4)
        self.cOrganization.setObjectName(u"cOrganization")
        self.cOrganization.setGeometry(QRect(120, 25, 200, 22))
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 30, 110, 16))
        self.cCity = QLineEdit(self.groupBox_4)
        self.cCity.setObjectName(u"cCity")
        self.cCity.setGeometry(QRect(120, 50, 200, 22))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 55, 110, 16))
        self.cCounty = QLineEdit(self.groupBox_4)
        self.cCounty.setObjectName(u"cCounty")
        self.cCounty.setGeometry(QRect(120, 75, 200, 22))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 80, 110, 16))
        self.cState = QLineEdit(self.groupBox_4)
        self.cState.setObjectName(u"cState")
        self.cState.setGeometry(QRect(120, 100, 60, 22))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 105, 110, 16))
        self.cTaticalLocation = QLineEdit(self.groupBox_4)
        self.cTaticalLocation.setObjectName(u"cTaticalLocation")
        self.cTaticalLocation.setGeometry(QRect(120, 125, 200, 22))
        self.label_6 = QLabel(self.groupBox_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 130, 110, 16))
        self.cTextVariable_2 = QLineEdit(self.groupBox_4)
        self.cTextVariable_2.setObjectName(u"cTextVariable_2")
        self.cTextVariable_2.setGeometry(QRect(120, 200, 200, 22))
        self.label_7 = QLabel(self.groupBox_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 205, 110, 16))
        self.cTextVariable_3 = QLineEdit(self.groupBox_4)
        self.cTextVariable_3.setObjectName(u"cTextVariable_3")
        self.cTextVariable_3.setGeometry(QRect(120, 225, 200, 22))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 230, 110, 16))
        self.cTaticalId = QLineEdit(self.groupBox_4)
        self.cTaticalId.setObjectName(u"cTaticalId")
        self.cTaticalId.setGeometry(QRect(120, 150, 50, 22))
        self.cTaticalId.setMaxLength(3)
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 155, 110, 16))
        self.cTaticalLocation_3 = QLineEdit(self.groupBox_4)
        self.cTaticalLocation_3.setObjectName(u"cTaticalLocation_3")
        self.cTaticalLocation_3.setGeometry(QRect(120, 175, 200, 22))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 180, 110, 16))
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(195, 155, 65, 16))
        self.cUserId = QLineEdit(self.groupBox_4)
        self.cUserId.setObjectName(u"cUserId")
        self.cUserId.setGeometry(QRect(265, 150, 50, 22))
        self.cUserId.setMaxLength(3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 450, 135))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 30, 49, 16))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 55, 49, 16))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 80, 49, 16))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 105, 49, 16))
        self.cF5File = QLineEdit(self.groupBox_2)
        self.cF5File.setObjectName(u"cF5File")
        self.cF5File.setGeometry(QRect(70, 25, 320, 22))
        self.cFindF5File = QPushButton(self.groupBox_2)
        self.cFindF5File.setObjectName(u"cFindF5File")
        self.cFindF5File.setGeometry(QRect(390, 25, 30, 22))
        self.cF6File = QLineEdit(self.groupBox_2)
        self.cF6File.setObjectName(u"cF6File")
        self.cF6File.setGeometry(QRect(70, 50, 320, 22))
        self.cFindF6File = QPushButton(self.groupBox_2)
        self.cFindF6File.setObjectName(u"cFindF6File")
        self.cFindF6File.setGeometry(QRect(390, 50, 30, 22))
        self.cF7File = QLineEdit(self.groupBox_2)
        self.cF7File.setObjectName(u"cF7File")
        self.cF7File.setGeometry(QRect(70, 75, 320, 22))
        self.cFindF7File = QPushButton(self.groupBox_2)
        self.cFindF7File.setObjectName(u"cFindF7File")
        self.cFindF7File.setGeometry(QRect(390, 75, 30, 22))
        self.cF8File = QLineEdit(self.groupBox_2)
        self.cF8File.setObjectName(u"cF8File")
        self.cF8File.setGeometry(QRect(70, 100, 320, 22))
        self.cFindF8File = QPushButton(self.groupBox_2)
        self.cFindF8File.setObjectName(u"cFindF8File")
        self.cFindF8File.setGeometry(QRect(390, 100, 30, 22))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_3 = QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 450, 330))
        self.tabWidget.addTab(self.tab_3, "")
        self.cOK = QPushButton(ReportSettingsDialogClass)
        self.cOK.setObjectName(u"cOK")
        self.cOK.setGeometry(QRect(330, 395, 75, 30))
        self.cCancel = QPushButton(ReportSettingsDialogClass)
        self.cCancel.setObjectName(u"cCancel")
        self.cCancel.setGeometry(QRect(405, 395, 75, 30))

        self.retranslateUi(ReportSettingsDialogClass)
        self.cOK.clicked.connect(ReportSettingsDialogClass.accept)
        self.cCancel.clicked.connect(ReportSettingsDialogClass.reject)

        self.tabWidget.setCurrentIndex(2)

    # setupUi

    def retranslateUi(self, ReportSettingsDialogClass):
        ReportSettingsDialogClass.setWindowTitle(QCoreApplication.translate("ReportSettingsDialogClass", u"ReportSettingsDialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("ReportSettingsDialogClass", u"Global Variables", None))
        self.label.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Next Message", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("ReportSettingsDialogClass", u"Report Variables, this profile", None))
        self.label_2.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Organization", None))
        self.label_3.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"City", None))
        self.label_4.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"County", None))
        self.label_5.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"State/Prov", None))
        self.label_6.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Tactical location", None))
        self.label_7.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Text variable #2", None))
        self.label_8.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Text variable #3", None))
        self.label_9.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Tactical ID", None))
        self.label_10.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Tactical name", None))
        self.label_11.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"User ID", None))
        self.cUserId.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("ReportSettingsDialogClass", u"Variables", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("ReportSettingsDialogClass", u"Fast Load Reports", None))
        self.label_12.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"F5", None))
        self.label_13.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"F6", None))
        self.label_14.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"F7", None))
        self.label_15.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"F8", None))
        self.cFindF5File.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"...", None))
        self.cFindF6File.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"...", None))
        self.cFindF7File.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"...", None))
        self.cFindF8File.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("ReportSettingsDialogClass", u"Reports", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("ReportSettingsDialogClass", u"Automation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("ReportSettingsDialogClass", u"ICS 309", None))
        self.cOK.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"OK", None))
        self.cCancel.setText(QCoreApplication.translate("ReportSettingsDialogClass", u"Cancel", None))
    # retranslateUi

