# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'stationiddialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTabWidget, QWidget)

class Ui_StationIdDialog(object):
    def setupUi(self, StationIdDialog):
        if not StationIdDialog.objectName():
            StationIdDialog.setObjectName(u"StationIdDialog")
        StationIdDialog.resize(490, 460)
        self.tabWidget = QTabWidget(StationIdDialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(5, 5, 480, 380))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 50, 450, 135))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 25, 135, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 135, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 75, 135, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 75, 135, 16))
        self.cUserCallSign = QComboBox(self.groupBox)
        self.cUserCallSign.setObjectName(u"cUserCallSign")
        self.cUserCallSign.setGeometry(QRect(145, 25, 135, 22))
        self.cUserCallSign.setEditable(False)
        self.cUserName = QLineEdit(self.groupBox)
        self.cUserName.setObjectName(u"cUserName")
        self.cUserName.setGeometry(QRect(145, 50, 160, 22))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 100, 135, 16))
        self.cUserMessageIdPrefix = QLineEdit(self.groupBox)
        self.cUserMessageIdPrefix.setObjectName(u"cUserMessageIdPrefix")
        self.cUserMessageIdPrefix.setGeometry(QRect(145, 75, 55, 22))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(145, 100, 80, 20))
        self.cNewUser = QPushButton(self.groupBox)
        self.cNewUser.setObjectName(u"cNewUser")
        self.cNewUser.setGeometry(QRect(340, 20, 75, 24))
        self.cDeleteUser = QPushButton(self.groupBox)
        self.cDeleteUser.setObjectName(u"cDeleteUser")
        self.cDeleteUser.setGeometry(QRect(340, 45, 75, 24))
        self.cCurrentProfile = QLineEdit(self.tab)
        self.cCurrentProfile.setObjectName(u"cCurrentProfile")
        self.cCurrentProfile.setEnabled(False)
        self.cCurrentProfile.setGeometry(QRect(155, 20, 295, 22))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 20, 110, 16))
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 195, 446, 146))
        self.cTacticalName = QLineEdit(self.groupBox_2)
        self.cTacticalName.setObjectName(u"cTacticalName")
        self.cTacticalName.setGeometry(QRect(145, 80, 160, 22))
        self.cNewTactical = QPushButton(self.groupBox_2)
        self.cNewTactical.setObjectName(u"cNewTactical")
        self.cNewTactical.setGeometry(QRect(345, 25, 75, 24))
        self.cTacticalCallSign = QComboBox(self.groupBox_2)
        self.cTacticalCallSign.setObjectName(u"cTacticalCallSign")
        self.cTacticalCallSign.setGeometry(QRect(145, 55, 135, 22))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(210, 105, 135, 16))
        self.cTacticalMessageIdPrefix = QLineEdit(self.groupBox_2)
        self.cTacticalMessageIdPrefix.setObjectName(u"cTacticalMessageIdPrefix")
        self.cTacticalMessageIdPrefix.setGeometry(QRect(145, 105, 55, 22))
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 105, 135, 16))
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 80, 135, 16))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 55, 135, 16))
        self.cDeleteTactical = QPushButton(self.groupBox_2)
        self.cDeleteTactical.setObjectName(u"cDeleteTactical")
        self.cDeleteTactical.setGeometry(QRect(345, 50, 75, 24))
        self.cUseTactical = QCheckBox(self.groupBox_2)
        self.cUseTactical.setObjectName(u"cUseTactical")
        self.cUseTactical.setGeometry(QRect(10, 30, 300, 20))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.cOK = QPushButton(StationIdDialog)
        self.cOK.setObjectName(u"cOK")
        self.cOK.setGeometry(QRect(310, 405, 75, 30))
        self.cCancel = QPushButton(StationIdDialog)
        self.cCancel.setObjectName(u"cCancel")
        self.cCancel.setGeometry(QRect(385, 405, 75, 30))
        self.cShowAtStartup = QCheckBox(StationIdDialog)
        self.cShowAtStartup.setObjectName(u"cShowAtStartup")
        self.cShowAtStartup.setGeometry(QRect(20, 410, 225, 20))

        self.retranslateUi(StationIdDialog)
        self.cOK.clicked.connect(StationIdDialog.accept)
        self.cCancel.clicked.connect(StationIdDialog.reject)

        self.tabWidget.setCurrentIndex(0)

    # setupUi

    def retranslateUi(self, StationIdDialog):
        StationIdDialog.setWindowTitle(QCoreApplication.translate("StationIdDialog", u"Station ID", None))
        self.groupBox.setTitle(QCoreApplication.translate("StationIdDialog", u"Legal", None))
        self.label.setText(QCoreApplication.translate("StationIdDialog", u"User call sign", None))
        self.label_2.setText(QCoreApplication.translate("StationIdDialog", u"User name", None))
        self.label_3.setText(QCoreApplication.translate("StationIdDialog", u"Message ID prefix", None))
        self.label_4.setText(QCoreApplication.translate("StationIdDialog", u"(3 characters max)", None))
        self.label_10.setText(QCoreApplication.translate("StationIdDialog", u"Transmit PST", None))
        self.checkBox.setText("")
        self.cNewUser.setText(QCoreApplication.translate("StationIdDialog", u"New", None))
        self.cDeleteUser.setText(QCoreApplication.translate("StationIdDialog", u"Delete", None))
        self.label_11.setText(QCoreApplication.translate("StationIdDialog", u"Current Profile", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("StationIdDialog", u"Tactical", None))
        self.cNewTactical.setText(QCoreApplication.translate("StationIdDialog", u"New", None))
        self.label_5.setText(QCoreApplication.translate("StationIdDialog", u"(3 characters max)", None))
        self.label_8.setText(QCoreApplication.translate("StationIdDialog", u"Message ID prefix", None))
        self.label_7.setText(QCoreApplication.translate("StationIdDialog", u"Tactical name", None))
        self.label_6.setText(QCoreApplication.translate("StationIdDialog", u"Tactical call sign", None))
        self.cDeleteTactical.setText(QCoreApplication.translate("StationIdDialog", u"Delete", None))
        self.cUseTactical.setText(QCoreApplication.translate("StationIdDialog", u"Use tactical call for all BBS interaction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("StationIdDialog", u"Identification", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("StationIdDialog", u"BBS Logins", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("StationIdDialog", u"Signatures", None))
        self.cOK.setText(QCoreApplication.translate("StationIdDialog", u"OK", None))
        self.cCancel.setText(QCoreApplication.translate("StationIdDialog", u"Cancel", None))
        self.cShowAtStartup.setText(QCoreApplication.translate("StationIdDialog", u"Show this form on startup", None))
    # retranslateUi

